#
# Copyright (c) 2024-2026. Foxikle
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
commands.no_permission=<red>Du hast keine Berechtigung dies zu tun\!
commands.manage.no_npcs=<red>Es gibt keine NPCs\!
commands.manage.header=<dark_green><st>                        </st> <gold>[<dark_aqua>\!</dark_aqua>] <dark_aqua><b>Verwalte NPCs</b></dark_aqua> [<dark_aqua>\!</dark_aqua>]</gold> <st>                       </st>
commands.manage.copy_uuid=<green>Klick um die UUID des NPCs zu kopieren.
commands.manage.button.edit=<b><yellow>[BEARBEITEN]
commands.manage.button.edit.hover=<dark_aqua>Klick um diesen NPC zu bearbeiten.
commands.manage.button.delete=<b><red>[ENTFERNEN]
commands.manage.button.delete.hover=<dark_aqua>Klick um den NPC permanent zu entfernen.
commands.clear_holograms.removed=<red>Dieser Befehl wurde in der Version 1.6.1 entfernt, da die NPC Hologramm Namen \u00FCberarbeitet wurden. Wenn du bestehende Hologramme entfernen m\u00F6chtest nutze\: /kill @e[tag\=npcHologram]
commands.reload.start=<yellow>Lade NPCs neu\!
commands.reload.end=<green>NPCs wurden erfolgreich neu geladen\!
commands.wiki=<yellow>Klick hier um das CustomNPCs Wiki zu \u00F6ffnen\!
commands.wiki.hover=<yellow>Klick um https\://docs.foxikle.dev/ aufzurufen\!
commands.setsound.unknown_sound=<red>Unbekannter Sound, bitte benutze die TAB Autovervollst\u00E4ndigung\!
commands.setsound.success=<green>Sound erfolgreich zu '<str>' ge\u00E4ndert
commands.setsound.was_not_waiting=<red>NPC Sound konnte nicht erfolgreich festgelegt werden. Ich habe nicht auf eine Antwort gewartet. Bitte kontaktiere Foxikle, falls du denkst, dass dies ein Fehler ist.
commands.invalid_uuid=<red>Die bereitgestellte UUID stimmt nicht mit der des NPCs \u00FCberein.
commands.invalid_name_or_uuid=<red>Falsche UUID oder Namen bereitgestellt.
commands.clone.success=<green>NPC erfolgreich geklont\!
commands.move.nudge=<italic><yellow>Psst\! Nach dem Entfernen von NPCs, solltest du sie neu laden\!
commands.unknown_command=<red> Unbekannter Unterbefehl. Nutze '/npc help' f\u00FCr eine Liste m\u00F6glicher Befehle.
commands.help.help.aliases=npc
commands.help.help.description=Diese Nachricht wird angezeigt.
commands.help.help.hover=Diese Nachricht wird angezeigt.
commands.help.manage.aliases=npc list
commands.help.manage.description=Listet die aktuellen NPCs auf
commands.help.manage.hover=Listet die aktuellen NPCs mit Kn\u00F6pfen auf, um sie zu bearbeiten oder zu entfernen.
commands.help.create.aliases=npc new
commands.help.create.description=\u00D6ffnet das NPC Anpassungsmen\u00FC mit einem neu erstellten NPC
commands.help.create.hover=Erstellt einen neuen NPC
commands.help.delete.aliases=Kein Alias
commands.help.delete.description=L\u00F6scht den NPC permanent
commands.help.delete.hover=L\u00F6scht den NPC dauerhaft und entfernt ihn aus der npcs.yml Datei. Er wird auch aus der Welt entfernt.
commands.help.edit.aliases=Kein Alias
commands.help.edit.description=Passt den ausgew\u00E4hlten NPC an
commands.help.edit.hover=\u00D6ffnet das NPC Anpassungsmen\u00FC
commands.help.movehere.aliases=Kein Alias
commands.help.movehere.description=Bewegt den NPC zu dir.
commands.help.movehere.hover=Klont den NPC und bewegt ihn an deine aktuelle Position. Sein Neigungswinkel (pitch) wird auf deinen aktuellen Neigungswinkel gesetzt. Auch sein Drehwinkel (yaw) wird auf deinen aktuellen Drehwinkel gesetzt.
commands.help.clone.aliases=Kein Alias
commands.help.clone.description=Klont den NPC und bewegt ihn zu dir.
commands.help.clone.hover=Klont den NPC und bewegt ihn an deine aktuelle Position. Sein Neigungswinkel (pitch) wird auf deinen aktuellen Neigungswinkel gesetzt. Auch sein Drehwinkel (yaw) wird auf deinen aktuellen Drehwinkel gesetzt.
commands.help.reload.aliases=Kein Alias
commands.help.reload.description=Reloads CustomNPCs
commands.help.goto.aliases=Kein Alias
commands.help.goto.description=Teleportiert dich zu den ausgew\u00E4hlten NPC.
commands.help.goto.hover=Teleportiert dich zu den ausgew\u00E4hlten NPC.
commands.help.wiki.description=Sendet ein Link zu den offiziellen CustomNPCs Wiki
commands.help.wiki.hover=Gibt Zugriff zum Wiki\!
commands.debug.message.enable=<green>Debugmodus aktiviert\!
commands.debug.message.disable=<green>Debugmodus deaktiviert\!
should_update=<green><st>----------------</st><reset> <gold>[<yellow>\!</yellow><gold>] <blue><b>CustomNPCs</b><gold> [<yellow>\!</yellow><gold>] <green><st>----------------</st><newline><reset><yellow>Ein neues Update ist verf\u00FCgbar\! Ich freue mich, wenn du aktualisierst \:)<newline><yellow><i>~Foxikle</i>
error.npc-menu-expired=<red><b>WHOOPS\!</b></red> <gray>Es sieht so aus als w\u00E4re ihr Men\u00FC-Instanz abgelaufen\! Sie k\u00F6nnen das Men\u00FC erneut \u00F6ffnen um dieses Problem zu beheben \:)
remove.description=<red>Rechtsklick um zu l\u00F6schen
edit.fail=<red>Diese Aktion kann nicht ge\u00E4ndert werden\!
skins.imported_by.url=Ein Skin \u00FCber URL importiert
data.command.title=<gold>Gib den Befehl in den Chat ein.
data.name.title=<gold>Gib den NPC Name in den Chat ein.
data.name.subtitle=<yellow>Nutzt MiniMessage Format
data.server.subtitle=<yellow>Hinweis\: Es sollte GENAU was die Bungeecord / Velocity Konfiguration ist.
menus.delete.items.confirm.name=<red><b>L\u00D6SCHEN
menus.delete.items.to_safety=<green>Zur\u00FCck zur Sicherheit\!
menus.main.title=<black>>        Ein neuen NPC erstellen




