// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: action.proto
// Protobuf Java Version: 4.28.3

package dev.foxikle.customnpcs.internal.proto;

public final class ActionOuterClass {
    private ActionOuterClass() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 28,
                /* patch= */ 3,
                /* suffix= */ "",
                ActionOuterClass.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ActionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:dev.foxikle.customnpcs.internal.proto.Action)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string serialized_data = 1;</code>
         *
         * @return The serializedData.
         */
        java.lang.String getSerializedData();

        /**
         * <code>string serialized_data = 1;</code>
         *
         * @return The bytes for serializedData.
         */
        com.google.protobuf.ByteString
        getSerializedDataBytes();
    }

    /**
     * <pre>
     * action doesn't need migration versions as thats handled by each individual action
     * </pre>
     * <p>
     * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Action}
     */
    public static final class Action extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:dev.foxikle.customnpcs.internal.proto.Action)
            ActionOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 28,
                    /* patch= */ 3,
                    /* suffix= */ "",
                    Action.class.getName());
        }

        // Use Action.newBuilder() to construct.
        private Action(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Action() {
            serializedData_ = "";
        }

        public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return dev.foxikle.customnpcs.internal.proto.ActionOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Action_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return dev.foxikle.customnpcs.internal.proto.ActionOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Action_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.class, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder.class);
        }

        public static final int SERIALIZED_DATA_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object serializedData_ = "";

        /**
         * <code>string serialized_data = 1;</code>
         *
         * @return The serializedData.
         */
        @java.lang.Override
        public java.lang.String getSerializedData() {
            java.lang.Object ref = serializedData_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                serializedData_ = s;
                return s;
            }
        }

        /**
         * <code>string serialized_data = 1;</code>
         *
         * @return The bytes for serializedData.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getSerializedDataBytes() {
            java.lang.Object ref = serializedData_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                serializedData_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serializedData_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, serializedData_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serializedData_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, serializedData_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Action other)) {
                return super.equals(obj);
            }

            if (!getSerializedData()
                    .equals(other.getSerializedData())) return false;
            return getUnknownFields().equals(other.getUnknownFields());
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SERIALIZED_DATA_FIELD_NUMBER;
            hash = (53 * hash) + getSerializedData().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * action doesn't need migration versions as thats handled by each individual action
         * </pre>
         * <p>
         * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Action}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:dev.foxikle.customnpcs.internal.proto.Action)
                dev.foxikle.customnpcs.internal.proto.ActionOuterClass.ActionOrBuilder {
            public static com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return dev.foxikle.customnpcs.internal.proto.ActionOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Action_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return dev.foxikle.customnpcs.internal.proto.ActionOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Action_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.class, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder.class);
            }

            // Construct using dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                serializedData_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return dev.foxikle.customnpcs.internal.proto.ActionOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Action_descriptor;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action getDefaultInstanceForType() {
                return dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.getDefaultInstance();
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action build() {
                dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action buildPartial() {
                dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action result = new dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.serializedData_ = serializedData_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action) {
                    return mergeFrom((dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action other) {
                if (other == dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.getDefaultInstance())
                    return this;
                if (!other.getSerializedData().isEmpty()) {
                    serializedData_ = other.serializedData_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                serializedData_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object serializedData_ = "";

            /**
             * <code>string serialized_data = 1;</code>
             *
             * @return The serializedData.
             */
            public java.lang.String getSerializedData() {
                java.lang.Object ref = serializedData_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    serializedData_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string serialized_data = 1;</code>
             *
             * @return The bytes for serializedData.
             */
            public com.google.protobuf.ByteString
            getSerializedDataBytes() {
                java.lang.Object ref = serializedData_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    serializedData_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string serialized_data = 1;</code>
             *
             * @param value The serializedData to set.
             * @return This builder for chaining.
             */
            public Builder setSerializedData(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                serializedData_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>string serialized_data = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSerializedData() {
                serializedData_ = getDefaultInstance().getSerializedData();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>string serialized_data = 1;</code>
             *
             * @param value The bytes for serializedData to set.
             * @return This builder for chaining.
             */
            public Builder setSerializedDataBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                serializedData_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:dev.foxikle.customnpcs.internal.proto.Action)
        }

        // @@protoc_insertion_point(class_scope:dev.foxikle.customnpcs.internal.proto.Action)
        private static final dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action();
        }

        public static dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Action>
                PARSER = new com.google.protobuf.AbstractParser<Action>() {
            @java.lang.Override
            public Action parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Action> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Action> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dev_foxikle_customnpcs_internal_proto_Action_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_dev_foxikle_customnpcs_internal_proto_Action_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\014action.proto\022%dev.foxikle.customnpcs.i" +
                        "nternal.proto\"!\n\006Action\022\027\n\017serialized_da" +
                        "ta\030\001 \001(\tb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_dev_foxikle_customnpcs_internal_proto_Action_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_dev_foxikle_customnpcs_internal_proto_Action_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_dev_foxikle_customnpcs_internal_proto_Action_descriptor,
                new java.lang.String[]{"SerializedData",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
