// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: equipment.proto
// Protobuf Java Version: 4.28.3

package dev.foxikle.customnpcs.internal.proto;

public final class EquipmentOuterClass {
    private EquipmentOuterClass() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 28,
                /* patch= */ 3,
                /* suffix= */ "",
                EquipmentOuterClass.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface EquipmentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:dev.foxikle.customnpcs.internal.proto.Equipment)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 schema_version = 1;</code>
         *
         * @return The schemaVersion.
         */
        int getSchemaVersion();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
         *
         * @return Whether the mainHand field is set.
         */
        boolean hasMainHand();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
         *
         * @return The mainHand.
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getMainHand();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getMainHandOrBuilder();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
         *
         * @return Whether the offHand field is set.
         */
        boolean hasOffHand();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
         *
         * @return The offHand.
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getOffHand();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getOffHandOrBuilder();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
         *
         * @return Whether the head field is set.
         */
        boolean hasHead();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
         *
         * @return The head.
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getHead();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getHeadOrBuilder();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
         *
         * @return Whether the chest field is set.
         */
        boolean hasChest();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
         *
         * @return The chest.
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getChest();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getChestOrBuilder();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
         *
         * @return Whether the legs field is set.
         */
        boolean hasLegs();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
         *
         * @return The legs.
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getLegs();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getLegsOrBuilder();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
         *
         * @return Whether the feet field is set.
         */
        boolean hasFeet();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
         *
         * @return The feet.
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getFeet();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
         */
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getFeetOrBuilder();
    }

    /**
     * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Equipment}
     */
    public static final class Equipment extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:dev.foxikle.customnpcs.internal.proto.Equipment)
            EquipmentOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 28,
                    /* patch= */ 3,
                    /* suffix= */ "",
                    Equipment.class.getName());
        }

        // Use Equipment.newBuilder() to construct.
        private Equipment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Equipment() {
        }

        public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Equipment_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Equipment_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.class, dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.Builder.class);
        }

        private int bitField0_;
        public static final int SCHEMA_VERSION_FIELD_NUMBER = 1;
        private int schemaVersion_ = 0;

        /**
         * <code>int32 schema_version = 1;</code>
         *
         * @return The schemaVersion.
         */
        @java.lang.Override
        public int getSchemaVersion() {
            return schemaVersion_;
        }

        public static final int MAIN_HAND_FIELD_NUMBER = 2;
        private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item mainHand_;

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
         *
         * @return Whether the mainHand field is set.
         */
        @java.lang.Override
        public boolean hasMainHand() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
         *
         * @return The mainHand.
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getMainHand() {
            return mainHand_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : mainHand_;
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getMainHandOrBuilder() {
            return mainHand_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : mainHand_;
        }

        public static final int OFF_HAND_FIELD_NUMBER = 3;
        private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item offHand_;

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
         *
         * @return Whether the offHand field is set.
         */
        @java.lang.Override
        public boolean hasOffHand() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
         *
         * @return The offHand.
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getOffHand() {
            return offHand_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : offHand_;
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getOffHandOrBuilder() {
            return offHand_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : offHand_;
        }

        public static final int HEAD_FIELD_NUMBER = 4;
        private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item head_;

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
         *
         * @return Whether the head field is set.
         */
        @java.lang.Override
        public boolean hasHead() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
         *
         * @return The head.
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getHead() {
            return head_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : head_;
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getHeadOrBuilder() {
            return head_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : head_;
        }

        public static final int CHEST_FIELD_NUMBER = 5;
        private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item chest_;

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
         *
         * @return Whether the chest field is set.
         */
        @java.lang.Override
        public boolean hasChest() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
         *
         * @return The chest.
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getChest() {
            return chest_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : chest_;
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getChestOrBuilder() {
            return chest_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : chest_;
        }

        public static final int LEGS_FIELD_NUMBER = 6;
        private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item legs_;

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
         *
         * @return Whether the legs field is set.
         */
        @java.lang.Override
        public boolean hasLegs() {
            return ((bitField0_ & 0x00000010) != 0);
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
         *
         * @return The legs.
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getLegs() {
            return legs_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : legs_;
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getLegsOrBuilder() {
            return legs_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : legs_;
        }

        public static final int FEET_FIELD_NUMBER = 7;
        private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item feet_;

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
         *
         * @return Whether the feet field is set.
         */
        @java.lang.Override
        public boolean hasFeet() {
            return ((bitField0_ & 0x00000020) != 0);
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
         *
         * @return The feet.
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getFeet() {
            return feet_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : feet_;
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getFeetOrBuilder() {
            return feet_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : feet_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (schemaVersion_ != 0) {
                output.writeInt32(1, schemaVersion_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(2, getMainHand());
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeMessage(3, getOffHand());
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                output.writeMessage(4, getHead());
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                output.writeMessage(5, getChest());
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                output.writeMessage(6, getLegs());
            }
            if (((bitField0_ & 0x00000020) != 0)) {
                output.writeMessage(7, getFeet());
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (schemaVersion_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, schemaVersion_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getMainHand());
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getOffHand());
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, getHead());
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(5, getChest());
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(6, getLegs());
            }
            if (((bitField0_ & 0x00000020) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(7, getFeet());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Equipment other)) {
                return super.equals(obj);
            }

            if (getSchemaVersion()
                    != other.getSchemaVersion()) return false;
            if (hasMainHand() != other.hasMainHand()) return false;
            if (hasMainHand()) {
                if (!getMainHand()
                        .equals(other.getMainHand())) return false;
            }
            if (hasOffHand() != other.hasOffHand()) return false;
            if (hasOffHand()) {
                if (!getOffHand()
                        .equals(other.getOffHand())) return false;
            }
            if (hasHead() != other.hasHead()) return false;
            if (hasHead()) {
                if (!getHead()
                        .equals(other.getHead())) return false;
            }
            if (hasChest() != other.hasChest()) return false;
            if (hasChest()) {
                if (!getChest()
                        .equals(other.getChest())) return false;
            }
            if (hasLegs() != other.hasLegs()) return false;
            if (hasLegs()) {
                if (!getLegs()
                        .equals(other.getLegs())) return false;
            }
            if (hasFeet() != other.hasFeet()) return false;
            if (hasFeet()) {
                if (!getFeet()
                        .equals(other.getFeet())) return false;
            }
            return getUnknownFields().equals(other.getUnknownFields());
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SCHEMA_VERSION_FIELD_NUMBER;
            hash = (53 * hash) + getSchemaVersion();
            if (hasMainHand()) {
                hash = (37 * hash) + MAIN_HAND_FIELD_NUMBER;
                hash = (53 * hash) + getMainHand().hashCode();
            }
            if (hasOffHand()) {
                hash = (37 * hash) + OFF_HAND_FIELD_NUMBER;
                hash = (53 * hash) + getOffHand().hashCode();
            }
            if (hasHead()) {
                hash = (37 * hash) + HEAD_FIELD_NUMBER;
                hash = (53 * hash) + getHead().hashCode();
            }
            if (hasChest()) {
                hash = (37 * hash) + CHEST_FIELD_NUMBER;
                hash = (53 * hash) + getChest().hashCode();
            }
            if (hasLegs()) {
                hash = (37 * hash) + LEGS_FIELD_NUMBER;
                hash = (53 * hash) + getLegs().hashCode();
            }
            if (hasFeet()) {
                hash = (37 * hash) + FEET_FIELD_NUMBER;
                hash = (53 * hash) + getFeet().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Equipment}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:dev.foxikle.customnpcs.internal.proto.Equipment)
                dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.EquipmentOrBuilder {
            public static com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Equipment_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Equipment_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.class, dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.Builder.class);
            }

            // Construct using dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage
                        .alwaysUseFieldBuilders) {
                    getMainHandFieldBuilder();
                    getOffHandFieldBuilder();
                    getHeadFieldBuilder();
                    getChestFieldBuilder();
                    getLegsFieldBuilder();
                    getFeetFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                schemaVersion_ = 0;
                mainHand_ = null;
                if (mainHandBuilder_ != null) {
                    mainHandBuilder_.dispose();
                    mainHandBuilder_ = null;
                }
                offHand_ = null;
                if (offHandBuilder_ != null) {
                    offHandBuilder_.dispose();
                    offHandBuilder_ = null;
                }
                head_ = null;
                if (headBuilder_ != null) {
                    headBuilder_.dispose();
                    headBuilder_ = null;
                }
                chest_ = null;
                if (chestBuilder_ != null) {
                    chestBuilder_.dispose();
                    chestBuilder_ = null;
                }
                legs_ = null;
                if (legsBuilder_ != null) {
                    legsBuilder_.dispose();
                    legsBuilder_ = null;
                }
                feet_ = null;
                if (feetBuilder_ != null) {
                    feetBuilder_.dispose();
                    feetBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Equipment_descriptor;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment getDefaultInstanceForType() {
                return dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.getDefaultInstance();
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment build() {
                dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment buildPartial() {
                dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment result = new dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.schemaVersion_ = schemaVersion_;
                }
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.mainHand_ = mainHandBuilder_ == null
                            ? mainHand_
                            : mainHandBuilder_.build();
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.offHand_ = offHandBuilder_ == null
                            ? offHand_
                            : offHandBuilder_.build();
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.head_ = headBuilder_ == null
                            ? head_
                            : headBuilder_.build();
                    to_bitField0_ |= 0x00000004;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.chest_ = chestBuilder_ == null
                            ? chest_
                            : chestBuilder_.build();
                    to_bitField0_ |= 0x00000008;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.legs_ = legsBuilder_ == null
                            ? legs_
                            : legsBuilder_.build();
                    to_bitField0_ |= 0x00000010;
                }
                if (((from_bitField0_ & 0x00000040) != 0)) {
                    result.feet_ = feetBuilder_ == null
                            ? feet_
                            : feetBuilder_.build();
                    to_bitField0_ |= 0x00000020;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment) {
                    return mergeFrom((dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment other) {
                if (other == dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.getDefaultInstance())
                    return this;
                if (other.getSchemaVersion() != 0) {
                    setSchemaVersion(other.getSchemaVersion());
                }
                if (other.hasMainHand()) {
                    mergeMainHand(other.getMainHand());
                }
                if (other.hasOffHand()) {
                    mergeOffHand(other.getOffHand());
                }
                if (other.hasHead()) {
                    mergeHead(other.getHead());
                }
                if (other.hasChest()) {
                    mergeChest(other.getChest());
                }
                if (other.hasLegs()) {
                    mergeLegs(other.getLegs());
                }
                if (other.hasFeet()) {
                    mergeFeet(other.getFeet());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                schemaVersion_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                input.readMessage(
                                        getMainHandFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26: {
                                input.readMessage(
                                        getOffHandFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 34: {
                                input.readMessage(
                                        getHeadFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 34
                            case 42: {
                                input.readMessage(
                                        getChestFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 42
                            case 50: {
                                input.readMessage(
                                        getLegsFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 50
                            case 58: {
                                input.readMessage(
                                        getFeetFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000040;
                                break;
                            } // case 58
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private int schemaVersion_;

            /**
             * <code>int32 schema_version = 1;</code>
             *
             * @return The schemaVersion.
             */
            @java.lang.Override
            public int getSchemaVersion() {
                return schemaVersion_;
            }

            /**
             * <code>int32 schema_version = 1;</code>
             *
             * @param value The schemaVersion to set.
             * @return This builder for chaining.
             */
            public Builder setSchemaVersion(int value) {

                schemaVersion_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>int32 schema_version = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSchemaVersion() {
                bitField0_ = (bitField0_ & ~0x00000001);
                schemaVersion_ = 0;
                onChanged();
                return this;
            }

            private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item mainHand_;
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder> mainHandBuilder_;

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
             *
             * @return Whether the mainHand field is set.
             */
            public boolean hasMainHand() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
             *
             * @return The mainHand.
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getMainHand() {
                if (mainHandBuilder_ == null) {
                    return mainHand_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : mainHand_;
                } else {
                    return mainHandBuilder_.getMessage();
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
             */
            public Builder setMainHand(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (mainHandBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    mainHand_ = value;
                } else {
                    mainHandBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
             */
            public Builder setMainHand(
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder builderForValue) {
                if (mainHandBuilder_ == null) {
                    mainHand_ = builderForValue.build();
                } else {
                    mainHandBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
             */
            public Builder mergeMainHand(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (mainHandBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) != 0) &&
                            mainHand_ != null &&
                            mainHand_ != dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance()) {
                        getMainHandBuilder().mergeFrom(value);
                    } else {
                        mainHand_ = value;
                    }
                } else {
                    mainHandBuilder_.mergeFrom(value);
                }
                if (mainHand_ != null) {
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
             */
            public Builder clearMainHand() {
                bitField0_ = (bitField0_ & ~0x00000002);
                mainHand_ = null;
                if (mainHandBuilder_ != null) {
                    mainHandBuilder_.dispose();
                    mainHandBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder getMainHandBuilder() {
                bitField0_ |= 0x00000002;
                onChanged();
                return getMainHandFieldBuilder().getBuilder();
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getMainHandOrBuilder() {
                if (mainHandBuilder_ != null) {
                    return mainHandBuilder_.getMessageOrBuilder();
                } else {
                    return mainHand_ == null ?
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : mainHand_;
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item main_hand = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>
            getMainHandFieldBuilder() {
                if (mainHandBuilder_ == null) {
                    mainHandBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>(
                            getMainHand(),
                            getParentForChildren(),
                            isClean());
                    mainHand_ = null;
                }
                return mainHandBuilder_;
            }

            private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item offHand_;
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder> offHandBuilder_;

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
             *
             * @return Whether the offHand field is set.
             */
            public boolean hasOffHand() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
             *
             * @return The offHand.
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getOffHand() {
                if (offHandBuilder_ == null) {
                    return offHand_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : offHand_;
                } else {
                    return offHandBuilder_.getMessage();
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
             */
            public Builder setOffHand(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (offHandBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    offHand_ = value;
                } else {
                    offHandBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
             */
            public Builder setOffHand(
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder builderForValue) {
                if (offHandBuilder_ == null) {
                    offHand_ = builderForValue.build();
                } else {
                    offHandBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
             */
            public Builder mergeOffHand(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (offHandBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) != 0) &&
                            offHand_ != null &&
                            offHand_ != dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance()) {
                        getOffHandBuilder().mergeFrom(value);
                    } else {
                        offHand_ = value;
                    }
                } else {
                    offHandBuilder_.mergeFrom(value);
                }
                if (offHand_ != null) {
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
             */
            public Builder clearOffHand() {
                bitField0_ = (bitField0_ & ~0x00000004);
                offHand_ = null;
                if (offHandBuilder_ != null) {
                    offHandBuilder_.dispose();
                    offHandBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder getOffHandBuilder() {
                bitField0_ |= 0x00000004;
                onChanged();
                return getOffHandFieldBuilder().getBuilder();
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getOffHandOrBuilder() {
                if (offHandBuilder_ != null) {
                    return offHandBuilder_.getMessageOrBuilder();
                } else {
                    return offHand_ == null ?
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : offHand_;
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item off_hand = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>
            getOffHandFieldBuilder() {
                if (offHandBuilder_ == null) {
                    offHandBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>(
                            getOffHand(),
                            getParentForChildren(),
                            isClean());
                    offHand_ = null;
                }
                return offHandBuilder_;
            }

            private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item head_;
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder> headBuilder_;

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
             *
             * @return Whether the head field is set.
             */
            public boolean hasHead() {
                return ((bitField0_ & 0x00000008) != 0);
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
             *
             * @return The head.
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getHead() {
                if (headBuilder_ == null) {
                    return head_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : head_;
                } else {
                    return headBuilder_.getMessage();
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
             */
            public Builder setHead(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (headBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    head_ = value;
                } else {
                    headBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
             */
            public Builder setHead(
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder builderForValue) {
                if (headBuilder_ == null) {
                    head_ = builderForValue.build();
                } else {
                    headBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
             */
            public Builder mergeHead(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (headBuilder_ == null) {
                    if (((bitField0_ & 0x00000008) != 0) &&
                            head_ != null &&
                            head_ != dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance()) {
                        getHeadBuilder().mergeFrom(value);
                    } else {
                        head_ = value;
                    }
                } else {
                    headBuilder_.mergeFrom(value);
                }
                if (head_ != null) {
                    bitField0_ |= 0x00000008;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
             */
            public Builder clearHead() {
                bitField0_ = (bitField0_ & ~0x00000008);
                head_ = null;
                if (headBuilder_ != null) {
                    headBuilder_.dispose();
                    headBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder getHeadBuilder() {
                bitField0_ |= 0x00000008;
                onChanged();
                return getHeadFieldBuilder().getBuilder();
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getHeadOrBuilder() {
                if (headBuilder_ != null) {
                    return headBuilder_.getMessageOrBuilder();
                } else {
                    return head_ == null ?
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : head_;
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item head = 4;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>
            getHeadFieldBuilder() {
                if (headBuilder_ == null) {
                    headBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>(
                            getHead(),
                            getParentForChildren(),
                            isClean());
                    head_ = null;
                }
                return headBuilder_;
            }

            private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item chest_;
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder> chestBuilder_;

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
             *
             * @return Whether the chest field is set.
             */
            public boolean hasChest() {
                return ((bitField0_ & 0x00000010) != 0);
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
             *
             * @return The chest.
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getChest() {
                if (chestBuilder_ == null) {
                    return chest_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : chest_;
                } else {
                    return chestBuilder_.getMessage();
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
             */
            public Builder setChest(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (chestBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    chest_ = value;
                } else {
                    chestBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
             */
            public Builder setChest(
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder builderForValue) {
                if (chestBuilder_ == null) {
                    chest_ = builderForValue.build();
                } else {
                    chestBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
             */
            public Builder mergeChest(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (chestBuilder_ == null) {
                    if (((bitField0_ & 0x00000010) != 0) &&
                            chest_ != null &&
                            chest_ != dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance()) {
                        getChestBuilder().mergeFrom(value);
                    } else {
                        chest_ = value;
                    }
                } else {
                    chestBuilder_.mergeFrom(value);
                }
                if (chest_ != null) {
                    bitField0_ |= 0x00000010;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
             */
            public Builder clearChest() {
                bitField0_ = (bitField0_ & ~0x00000010);
                chest_ = null;
                if (chestBuilder_ != null) {
                    chestBuilder_.dispose();
                    chestBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder getChestBuilder() {
                bitField0_ |= 0x00000010;
                onChanged();
                return getChestFieldBuilder().getBuilder();
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getChestOrBuilder() {
                if (chestBuilder_ != null) {
                    return chestBuilder_.getMessageOrBuilder();
                } else {
                    return chest_ == null ?
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : chest_;
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item chest = 5;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>
            getChestFieldBuilder() {
                if (chestBuilder_ == null) {
                    chestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>(
                            getChest(),
                            getParentForChildren(),
                            isClean());
                    chest_ = null;
                }
                return chestBuilder_;
            }

            private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item legs_;
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder> legsBuilder_;

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
             *
             * @return Whether the legs field is set.
             */
            public boolean hasLegs() {
                return ((bitField0_ & 0x00000020) != 0);
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
             *
             * @return The legs.
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getLegs() {
                if (legsBuilder_ == null) {
                    return legs_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : legs_;
                } else {
                    return legsBuilder_.getMessage();
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
             */
            public Builder setLegs(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (legsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    legs_ = value;
                } else {
                    legsBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
             */
            public Builder setLegs(
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder builderForValue) {
                if (legsBuilder_ == null) {
                    legs_ = builderForValue.build();
                } else {
                    legsBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
             */
            public Builder mergeLegs(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (legsBuilder_ == null) {
                    if (((bitField0_ & 0x00000020) != 0) &&
                            legs_ != null &&
                            legs_ != dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance()) {
                        getLegsBuilder().mergeFrom(value);
                    } else {
                        legs_ = value;
                    }
                } else {
                    legsBuilder_.mergeFrom(value);
                }
                if (legs_ != null) {
                    bitField0_ |= 0x00000020;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
             */
            public Builder clearLegs() {
                bitField0_ = (bitField0_ & ~0x00000020);
                legs_ = null;
                if (legsBuilder_ != null) {
                    legsBuilder_.dispose();
                    legsBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder getLegsBuilder() {
                bitField0_ |= 0x00000020;
                onChanged();
                return getLegsFieldBuilder().getBuilder();
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getLegsOrBuilder() {
                if (legsBuilder_ != null) {
                    return legsBuilder_.getMessageOrBuilder();
                } else {
                    return legs_ == null ?
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : legs_;
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item legs = 6;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>
            getLegsFieldBuilder() {
                if (legsBuilder_ == null) {
                    legsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>(
                            getLegs(),
                            getParentForChildren(),
                            isClean());
                    legs_ = null;
                }
                return legsBuilder_;
            }

            private dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item feet_;
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder> feetBuilder_;

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
             *
             * @return Whether the feet field is set.
             */
            public boolean hasFeet() {
                return ((bitField0_ & 0x00000040) != 0);
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
             *
             * @return The feet.
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getFeet() {
                if (feetBuilder_ == null) {
                    return feet_ == null ? dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : feet_;
                } else {
                    return feetBuilder_.getMessage();
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
             */
            public Builder setFeet(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (feetBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    feet_ = value;
                } else {
                    feetBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
             */
            public Builder setFeet(
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder builderForValue) {
                if (feetBuilder_ == null) {
                    feet_ = builderForValue.build();
                } else {
                    feetBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
             */
            public Builder mergeFeet(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item value) {
                if (feetBuilder_ == null) {
                    if (((bitField0_ & 0x00000040) != 0) &&
                            feet_ != null &&
                            feet_ != dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance()) {
                        getFeetBuilder().mergeFrom(value);
                    } else {
                        feet_ = value;
                    }
                } else {
                    feetBuilder_.mergeFrom(value);
                }
                if (feet_ != null) {
                    bitField0_ |= 0x00000040;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
             */
            public Builder clearFeet() {
                bitField0_ = (bitField0_ & ~0x00000040);
                feet_ = null;
                if (feetBuilder_ != null) {
                    feetBuilder_.dispose();
                    feetBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder getFeetBuilder() {
                bitField0_ |= 0x00000040;
                onChanged();
                return getFeetFieldBuilder().getBuilder();
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder getFeetOrBuilder() {
                if (feetBuilder_ != null) {
                    return feetBuilder_.getMessageOrBuilder();
                } else {
                    return feet_ == null ?
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance() : feet_;
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Item feet = 7;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>
            getFeetFieldBuilder() {
                if (feetBuilder_ == null) {
                    feetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder>(
                            getFeet(),
                            getParentForChildren(),
                            isClean());
                    feet_ = null;
                }
                return feetBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:dev.foxikle.customnpcs.internal.proto.Equipment)
        }

        // @@protoc_insertion_point(class_scope:dev.foxikle.customnpcs.internal.proto.Equipment)
        private static final dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment();
        }

        public static dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Equipment>
                PARSER = new com.google.protobuf.AbstractParser<Equipment>() {
            @java.lang.Override
            public Equipment parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Equipment> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Equipment> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dev_foxikle_customnpcs_internal_proto_Equipment_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_dev_foxikle_customnpcs_internal_proto_Equipment_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\017equipment.proto\022%dev.foxikle.customnpc" +
                        "s.internal.proto\032\nitem.proto\"\217\003\n\tEquipme" +
                        "nt\022\026\n\016schema_version\030\001 \001(\005\022>\n\tmain_hand\030" +
                        "\002 \001(\0132+.dev.foxikle.customnpcs.internal." +
                        "proto.Item\022=\n\010off_hand\030\003 \001(\0132+.dev.foxik" +
                        "le.customnpcs.internal.proto.Item\0229\n\004hea" +
                        "d\030\004 \001(\0132+.dev.foxikle.customnpcs.interna" +
                        "l.proto.Item\022:\n\005chest\030\005 \001(\0132+.dev.foxikl" +
                        "e.customnpcs.internal.proto.Item\0229\n\004legs" +
                        "\030\006 \001(\0132+.dev.foxikle.customnpcs.internal" +
                        ".proto.Item\0229\n\004feet\030\007 \001(\0132+.dev.foxikle." +
                        "customnpcs.internal.proto.Itemb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                dev.foxikle.customnpcs.internal.proto.ItemOuterClass.getDescriptor(),
                        });
        internal_static_dev_foxikle_customnpcs_internal_proto_Equipment_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_dev_foxikle_customnpcs_internal_proto_Equipment_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_dev_foxikle_customnpcs_internal_proto_Equipment_descriptor,
                new java.lang.String[]{"SchemaVersion", "MainHand", "OffHand", "Head", "Chest", "Legs", "Feet",});
        descriptor.resolveAllFeaturesImmutable();
        dev.foxikle.customnpcs.internal.proto.ItemOuterClass.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
