// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: item.proto
// Protobuf Java Version: 4.28.3

package dev.foxikle.customnpcs.internal.proto;

public final class ItemOuterClass {
    private ItemOuterClass() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 28,
                /* patch= */ 3,
                /* suffix= */ "",
                ItemOuterClass.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ItemOrBuilder extends
            // @@protoc_insertion_point(interface_extends:dev.foxikle.customnpcs.internal.proto.Item)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * byte array
         * </pre>
         *
         * <code>bytes serialized = 1;</code>
         *
         * @return The serialized.
         */
        com.google.protobuf.ByteString getSerialized();
    }

    /**
     * <pre>
     * doesn't need a migrations field as that is already handled by Paper's itemstack serialization
     * </pre>
     * <p>
     * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Item}
     */
    public static final class Item extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:dev.foxikle.customnpcs.internal.proto.Item)
            ItemOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 28,
                    /* patch= */ 3,
                    /* suffix= */ "",
                    Item.class.getName());
        }

        // Use Item.newBuilder() to construct.
        private Item(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Item() {
            serialized_ = com.google.protobuf.ByteString.EMPTY;
        }

        public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return dev.foxikle.customnpcs.internal.proto.ItemOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Item_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return dev.foxikle.customnpcs.internal.proto.ItemOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Item_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.class, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder.class);
        }

        public static final int SERIALIZED_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString serialized_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <pre>
         * byte array
         * </pre>
         *
         * <code>bytes serialized = 1;</code>
         *
         * @return The serialized.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getSerialized() {
            return serialized_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!serialized_.isEmpty()) {
                output.writeBytes(1, serialized_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!serialized_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, serialized_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Item other)) {
                return super.equals(obj);
            }

            if (!getSerialized()
                    .equals(other.getSerialized())) return false;
            return getUnknownFields().equals(other.getUnknownFields());
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SERIALIZED_FIELD_NUMBER;
            hash = (53 * hash) + getSerialized().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * doesn't need a migrations field as that is already handled by Paper's itemstack serialization
         * </pre>
         * <p>
         * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Item}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:dev.foxikle.customnpcs.internal.proto.Item)
                dev.foxikle.customnpcs.internal.proto.ItemOuterClass.ItemOrBuilder {
            public static com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return dev.foxikle.customnpcs.internal.proto.ItemOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Item_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return dev.foxikle.customnpcs.internal.proto.ItemOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Item_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.class, dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.Builder.class);
            }

            // Construct using dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                serialized_ = com.google.protobuf.ByteString.EMPTY;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return dev.foxikle.customnpcs.internal.proto.ItemOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Item_descriptor;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getDefaultInstanceForType() {
                return dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance();
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item build() {
                dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item buildPartial() {
                dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item result = new dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.serialized_ = serialized_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item) {
                    return mergeFrom((dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item other) {
                if (other == dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item.getDefaultInstance())
                    return this;
                if (other.getSerialized() != com.google.protobuf.ByteString.EMPTY) {
                    setSerialized(other.getSerialized());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                serialized_ = input.readBytes();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.ByteString serialized_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * byte array
             * </pre>
             *
             * <code>bytes serialized = 1;</code>
             *
             * @return The serialized.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getSerialized() {
                return serialized_;
            }

            /**
             * <pre>
             * byte array
             * </pre>
             *
             * <code>bytes serialized = 1;</code>
             *
             * @param value The serialized to set.
             * @return This builder for chaining.
             */
            public Builder setSerialized(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                serialized_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * byte array
             * </pre>
             *
             * <code>bytes serialized = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSerialized() {
                bitField0_ = (bitField0_ & ~0x00000001);
                serialized_ = getDefaultInstance().getSerialized();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:dev.foxikle.customnpcs.internal.proto.Item)
        }

        // @@protoc_insertion_point(class_scope:dev.foxikle.customnpcs.internal.proto.Item)
        private static final dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item();
        }

        public static dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Item>
                PARSER = new com.google.protobuf.AbstractParser<Item>() {
            @java.lang.Override
            public Item parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Item> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Item> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ItemOuterClass.Item getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dev_foxikle_customnpcs_internal_proto_Item_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_dev_foxikle_customnpcs_internal_proto_Item_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\nitem.proto\022%dev.foxikle.customnpcs.int" +
                        "ernal.proto\"\032\n\004Item\022\022\n\nserialized\030\001 \001(\014b" +
                        "\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_dev_foxikle_customnpcs_internal_proto_Item_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_dev_foxikle_customnpcs_internal_proto_Item_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_dev_foxikle_customnpcs_internal_proto_Item_descriptor,
                new java.lang.String[]{"Serialized",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
