// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: location.proto
// Protobuf Java Version: 4.28.3

package dev.foxikle.customnpcs.internal.proto;

public final class LocationOuterClass {
    private LocationOuterClass() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 28,
                /* patch= */ 3,
                /* suffix= */ "",
                LocationOuterClass.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface LocationOrBuilder extends
            // @@protoc_insertion_point(interface_extends:dev.foxikle.customnpcs.internal.proto.Location)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 schema_version = 1;</code>
         *
         * @return The schemaVersion.
         */
        int getSchemaVersion();

        /**
         * <code>string world = 2;</code>
         *
         * @return The world.
         */
        java.lang.String getWorld();

        /**
         * <code>string world = 2;</code>
         *
         * @return The bytes for world.
         */
        com.google.protobuf.ByteString
        getWorldBytes();

        /**
         * <code>double x = 3;</code>
         *
         * @return The x.
         */
        double getX();

        /**
         * <code>double y = 4;</code>
         *
         * @return The y.
         */
        double getY();

        /**
         * <code>double z = 5;</code>
         *
         * @return The z.
         */
        double getZ();

        /**
         * <code>float pitch = 6;</code>
         *
         * @return The pitch.
         */
        float getPitch();

        /**
         * <code>float yaw = 7;</code>
         *
         * @return The yaw.
         */
        float getYaw();
    }

    /**
     * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Location}
     */
    public static final class Location extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:dev.foxikle.customnpcs.internal.proto.Location)
            LocationOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 28,
                    /* patch= */ 3,
                    /* suffix= */ "",
                    Location.class.getName());
        }

        // Use Location.newBuilder() to construct.
        private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Location() {
            world_ = "";
        }

        public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return dev.foxikle.customnpcs.internal.proto.LocationOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Location_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return dev.foxikle.customnpcs.internal.proto.LocationOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Location_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.class, dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.Builder.class);
        }

        public static final int SCHEMA_VERSION_FIELD_NUMBER = 1;
        private int schemaVersion_ = 0;

        /**
         * <code>int32 schema_version = 1;</code>
         *
         * @return The schemaVersion.
         */
        @java.lang.Override
        public int getSchemaVersion() {
            return schemaVersion_;
        }

        public static final int WORLD_FIELD_NUMBER = 2;
        @SuppressWarnings("serial")
        private volatile java.lang.Object world_ = "";

        /**
         * <code>string world = 2;</code>
         *
         * @return The world.
         */
        @java.lang.Override
        public java.lang.String getWorld() {
            java.lang.Object ref = world_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                world_ = s;
                return s;
            }
        }

        /**
         * <code>string world = 2;</code>
         *
         * @return The bytes for world.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getWorldBytes() {
            java.lang.Object ref = world_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                world_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int X_FIELD_NUMBER = 3;
        private double x_ = 0D;

        /**
         * <code>double x = 3;</code>
         *
         * @return The x.
         */
        @java.lang.Override
        public double getX() {
            return x_;
        }

        public static final int Y_FIELD_NUMBER = 4;
        private double y_ = 0D;

        /**
         * <code>double y = 4;</code>
         *
         * @return The y.
         */
        @java.lang.Override
        public double getY() {
            return y_;
        }

        public static final int Z_FIELD_NUMBER = 5;
        private double z_ = 0D;

        /**
         * <code>double z = 5;</code>
         *
         * @return The z.
         */
        @java.lang.Override
        public double getZ() {
            return z_;
        }

        public static final int PITCH_FIELD_NUMBER = 6;
        private float pitch_ = 0F;

        /**
         * <code>float pitch = 6;</code>
         *
         * @return The pitch.
         */
        @java.lang.Override
        public float getPitch() {
            return pitch_;
        }

        public static final int YAW_FIELD_NUMBER = 7;
        private float yaw_ = 0F;

        /**
         * <code>float yaw = 7;</code>
         *
         * @return The yaw.
         */
        @java.lang.Override
        public float getYaw() {
            return yaw_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (schemaVersion_ != 0) {
                output.writeInt32(1, schemaVersion_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(world_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 2, world_);
            }
            if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
                output.writeDouble(3, x_);
            }
            if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
                output.writeDouble(4, y_);
            }
            if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
                output.writeDouble(5, z_);
            }
            if (java.lang.Float.floatToRawIntBits(pitch_) != 0) {
                output.writeFloat(6, pitch_);
            }
            if (java.lang.Float.floatToRawIntBits(yaw_) != 0) {
                output.writeFloat(7, yaw_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (schemaVersion_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, schemaVersion_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(world_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(2, world_);
            }
            if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(3, x_);
            }
            if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(4, y_);
            }
            if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(5, z_);
            }
            if (java.lang.Float.floatToRawIntBits(pitch_) != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(6, pitch_);
            }
            if (java.lang.Float.floatToRawIntBits(yaw_) != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(7, yaw_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Location other)) {
                return super.equals(obj);
            }

            if (getSchemaVersion()
                    != other.getSchemaVersion()) return false;
            if (!getWorld()
                    .equals(other.getWorld())) return false;
            if (java.lang.Double.doubleToLongBits(getX())
                    != java.lang.Double.doubleToLongBits(
                    other.getX())) return false;
            if (java.lang.Double.doubleToLongBits(getY())
                    != java.lang.Double.doubleToLongBits(
                    other.getY())) return false;
            if (java.lang.Double.doubleToLongBits(getZ())
                    != java.lang.Double.doubleToLongBits(
                    other.getZ())) return false;
            if (java.lang.Float.floatToIntBits(getPitch())
                    != java.lang.Float.floatToIntBits(
                    other.getPitch())) return false;
            if (java.lang.Float.floatToIntBits(getYaw())
                    != java.lang.Float.floatToIntBits(
                    other.getYaw())) return false;
            return getUnknownFields().equals(other.getUnknownFields());
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SCHEMA_VERSION_FIELD_NUMBER;
            hash = (53 * hash) + getSchemaVersion();
            hash = (37 * hash) + WORLD_FIELD_NUMBER;
            hash = (53 * hash) + getWorld().hashCode();
            hash = (37 * hash) + X_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getX()));
            hash = (37 * hash) + Y_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getY()));
            hash = (37 * hash) + Z_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getZ()));
            hash = (37 * hash) + PITCH_FIELD_NUMBER;
            hash = (53 * hash) + java.lang.Float.floatToIntBits(
                    getPitch());
            hash = (37 * hash) + YAW_FIELD_NUMBER;
            hash = (53 * hash) + java.lang.Float.floatToIntBits(
                    getYaw());
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Location}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:dev.foxikle.customnpcs.internal.proto.Location)
                dev.foxikle.customnpcs.internal.proto.LocationOuterClass.LocationOrBuilder {
            public static com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return dev.foxikle.customnpcs.internal.proto.LocationOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Location_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return dev.foxikle.customnpcs.internal.proto.LocationOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Location_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.class, dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.Builder.class);
            }

            // Construct using dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                schemaVersion_ = 0;
                world_ = "";
                x_ = 0D;
                y_ = 0D;
                z_ = 0D;
                pitch_ = 0F;
                yaw_ = 0F;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return dev.foxikle.customnpcs.internal.proto.LocationOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Location_descriptor;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location getDefaultInstanceForType() {
                return dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.getDefaultInstance();
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location build() {
                dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location buildPartial() {
                dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location result = new dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.schemaVersion_ = schemaVersion_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.world_ = world_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.x_ = x_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.y_ = y_;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.z_ = z_;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.pitch_ = pitch_;
                }
                if (((from_bitField0_ & 0x00000040) != 0)) {
                    result.yaw_ = yaw_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location) {
                    return mergeFrom((dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location other) {
                if (other == dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.getDefaultInstance())
                    return this;
                if (other.getSchemaVersion() != 0) {
                    setSchemaVersion(other.getSchemaVersion());
                }
                if (!other.getWorld().isEmpty()) {
                    world_ = other.world_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                if (other.getX() != 0D) {
                    setX(other.getX());
                }
                if (other.getY() != 0D) {
                    setY(other.getY());
                }
                if (other.getZ() != 0D) {
                    setZ(other.getZ());
                }
                if (other.getPitch() != 0F) {
                    setPitch(other.getPitch());
                }
                if (other.getYaw() != 0F) {
                    setYaw(other.getYaw());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                schemaVersion_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                world_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 25: {
                                x_ = input.readDouble();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 25
                            case 33: {
                                y_ = input.readDouble();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 33
                            case 41: {
                                z_ = input.readDouble();
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 41
                            case 53: {
                                pitch_ = input.readFloat();
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 53
                            case 61: {
                                yaw_ = input.readFloat();
                                bitField0_ |= 0x00000040;
                                break;
                            } // case 61
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private int schemaVersion_;

            /**
             * <code>int32 schema_version = 1;</code>
             *
             * @return The schemaVersion.
             */
            @java.lang.Override
            public int getSchemaVersion() {
                return schemaVersion_;
            }

            /**
             * <code>int32 schema_version = 1;</code>
             *
             * @param value The schemaVersion to set.
             * @return This builder for chaining.
             */
            public Builder setSchemaVersion(int value) {

                schemaVersion_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>int32 schema_version = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSchemaVersion() {
                bitField0_ = (bitField0_ & ~0x00000001);
                schemaVersion_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object world_ = "";

            /**
             * <code>string world = 2;</code>
             *
             * @return The world.
             */
            public java.lang.String getWorld() {
                java.lang.Object ref = world_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    world_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string world = 2;</code>
             *
             * @return The bytes for world.
             */
            public com.google.protobuf.ByteString
            getWorldBytes() {
                java.lang.Object ref = world_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    world_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string world = 2;</code>
             *
             * @param value The world to set.
             * @return This builder for chaining.
             */
            public Builder setWorld(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                world_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string world = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearWorld() {
                world_ = getDefaultInstance().getWorld();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <code>string world = 2;</code>
             *
             * @param value The bytes for world to set.
             * @return This builder for chaining.
             */
            public Builder setWorldBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                world_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            private double x_;

            /**
             * <code>double x = 3;</code>
             *
             * @return The x.
             */
            @java.lang.Override
            public double getX() {
                return x_;
            }

            /**
             * <code>double x = 3;</code>
             *
             * @param value The x to set.
             * @return This builder for chaining.
             */
            public Builder setX(double value) {

                x_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>double x = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearX() {
                bitField0_ = (bitField0_ & ~0x00000004);
                x_ = 0D;
                onChanged();
                return this;
            }

            private double y_;

            /**
             * <code>double y = 4;</code>
             *
             * @return The y.
             */
            @java.lang.Override
            public double getY() {
                return y_;
            }

            /**
             * <code>double y = 4;</code>
             *
             * @param value The y to set.
             * @return This builder for chaining.
             */
            public Builder setY(double value) {

                y_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>double y = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearY() {
                bitField0_ = (bitField0_ & ~0x00000008);
                y_ = 0D;
                onChanged();
                return this;
            }

            private double z_;

            /**
             * <code>double z = 5;</code>
             *
             * @return The z.
             */
            @java.lang.Override
            public double getZ() {
                return z_;
            }

            /**
             * <code>double z = 5;</code>
             *
             * @param value The z to set.
             * @return This builder for chaining.
             */
            public Builder setZ(double value) {

                z_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>double z = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearZ() {
                bitField0_ = (bitField0_ & ~0x00000010);
                z_ = 0D;
                onChanged();
                return this;
            }

            private float pitch_;

            /**
             * <code>float pitch = 6;</code>
             *
             * @return The pitch.
             */
            @java.lang.Override
            public float getPitch() {
                return pitch_;
            }

            /**
             * <code>float pitch = 6;</code>
             *
             * @param value The pitch to set.
             * @return This builder for chaining.
             */
            public Builder setPitch(float value) {

                pitch_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <code>float pitch = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPitch() {
                bitField0_ = (bitField0_ & ~0x00000020);
                pitch_ = 0F;
                onChanged();
                return this;
            }

            private float yaw_;

            /**
             * <code>float yaw = 7;</code>
             *
             * @return The yaw.
             */
            @java.lang.Override
            public float getYaw() {
                return yaw_;
            }

            /**
             * <code>float yaw = 7;</code>
             *
             * @param value The yaw to set.
             * @return This builder for chaining.
             */
            public Builder setYaw(float value) {

                yaw_ = value;
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            /**
             * <code>float yaw = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearYaw() {
                bitField0_ = (bitField0_ & ~0x00000040);
                yaw_ = 0F;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:dev.foxikle.customnpcs.internal.proto.Location)
        }

        // @@protoc_insertion_point(class_scope:dev.foxikle.customnpcs.internal.proto.Location)
        private static final dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location();
        }

        public static dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Location>
                PARSER = new com.google.protobuf.AbstractParser<Location>() {
            @java.lang.Override
            public Location parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Location> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Location> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dev_foxikle_customnpcs_internal_proto_Location_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_dev_foxikle_customnpcs_internal_proto_Location_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016location.proto\022%dev.foxikle.customnpcs" +
                        ".internal.proto\"n\n\010Location\022\026\n\016schema_ve" +
                        "rsion\030\001 \001(\005\022\r\n\005world\030\002 \001(\t\022\t\n\001x\030\003 \001(\001\022\t\n" +
                        "\001y\030\004 \001(\001\022\t\n\001z\030\005 \001(\001\022\r\n\005pitch\030\006 \001(\002\022\013\n\003ya" +
                        "w\030\007 \001(\002b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_dev_foxikle_customnpcs_internal_proto_Location_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_dev_foxikle_customnpcs_internal_proto_Location_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_dev_foxikle_customnpcs_internal_proto_Location_descriptor,
                new java.lang.String[]{"SchemaVersion", "World", "X", "Y", "Z", "Pitch", "Yaw",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
