// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: npc_list.proto
// Protobuf Java Version: 4.28.3

package dev.foxikle.customnpcs.internal.proto;

public final class NpcListOuterClass {
    private NpcListOuterClass() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 28,
                /* patch= */ 3,
                /* suffix= */ "",
                NpcListOuterClass.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface NpcListOrBuilder extends
            // @@protoc_insertion_point(interface_extends:dev.foxikle.customnpcs.internal.proto.NpcList)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
         */
        java.util.List<dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc>
        getNpcsList();

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
         */
        dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc getNpcs(int index);

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
         */
        int getNpcsCount();

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
         */
        java.util.List<? extends dev.foxikle.customnpcs.internal.proto.NpcOuterClass.NpcOrBuilder>
        getNpcsOrBuilderList();

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
         */
        dev.foxikle.customnpcs.internal.proto.NpcOuterClass.NpcOrBuilder getNpcsOrBuilder(
                int index);
    }

    /**
     * <pre>
     * This is the data that gets stored in a file or database somewhere,
     * </pre>
     * <p>
     * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.NpcList}
     */
    public static final class NpcList extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:dev.foxikle.customnpcs.internal.proto.NpcList)
            NpcListOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 28,
                    /* patch= */ 3,
                    /* suffix= */ "",
                    NpcList.class.getName());
        }

        // Use NpcList.newBuilder() to construct.
        private NpcList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private NpcList() {
            npcs_ = java.util.Collections.emptyList();
        }

        public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_NpcList_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_NpcList_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList.class, dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList.Builder.class);
        }

        public static final int NPCS_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private java.util.List<dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc> npcs_;

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
         */
        @java.lang.Override
        public java.util.List<dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc> getNpcsList() {
            return npcs_;
        }

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
         */
        @java.lang.Override
        public java.util.List<? extends dev.foxikle.customnpcs.internal.proto.NpcOuterClass.NpcOrBuilder>
        getNpcsOrBuilderList() {
            return npcs_;
        }

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
         */
        @java.lang.Override
        public int getNpcsCount() {
            return npcs_.size();
        }

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc getNpcs(int index) {
            return npcs_.get(index);
        }

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.NpcOuterClass.NpcOrBuilder getNpcsOrBuilder(
                int index) {
            return npcs_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < npcs_.size(); i++) {
                output.writeMessage(1, npcs_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < npcs_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, npcs_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof NpcList other)) {
                return super.equals(obj);
            }

            if (!getNpcsList()
                    .equals(other.getNpcsList())) return false;
            return getUnknownFields().equals(other.getUnknownFields());
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getNpcsCount() > 0) {
                hash = (37 * hash) + NPCS_FIELD_NUMBER;
                hash = (53 * hash) + getNpcsList().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * This is the data that gets stored in a file or database somewhere,
         * </pre>
         * <p>
         * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.NpcList}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:dev.foxikle.customnpcs.internal.proto.NpcList)
                dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcListOrBuilder {
            public static com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_NpcList_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_NpcList_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList.class, dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList.Builder.class);
            }

            // Construct using dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                if (npcsBuilder_ == null) {
                    npcs_ = java.util.Collections.emptyList();
                } else {
                    npcs_ = null;
                    npcsBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_NpcList_descriptor;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList getDefaultInstanceForType() {
                return dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList.getDefaultInstance();
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList build() {
                dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList buildPartial() {
                dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList result = new dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList(this);
                buildPartialRepeatedFields(result);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartialRepeatedFields(dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList result) {
                if (npcsBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        npcs_ = java.util.Collections.unmodifiableList(npcs_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.npcs_ = npcs_;
                } else {
                    result.npcs_ = npcsBuilder_.build();
                }
            }

            private void buildPartial0(dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList result) {
                int from_bitField0_ = bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList) {
                    return mergeFrom((dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList other) {
                if (other == dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList.getDefaultInstance())
                    return this;
                if (npcsBuilder_ == null) {
                    if (!other.npcs_.isEmpty()) {
                        if (npcs_.isEmpty()) {
                            npcs_ = other.npcs_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureNpcsIsMutable();
                            npcs_.addAll(other.npcs_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.npcs_.isEmpty()) {
                        if (npcsBuilder_.isEmpty()) {
                            npcsBuilder_.dispose();
                            npcsBuilder_ = null;
                            npcs_ = other.npcs_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            npcsBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getNpcsFieldBuilder() : null;
                        } else {
                            npcsBuilder_.addAllMessages(other.npcs_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc m =
                                        input.readMessage(
                                                dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.parser(),
                                                extensionRegistry);
                                if (npcsBuilder_ == null) {
                                    ensureNpcsIsMutable();
                                    npcs_.add(m);
                                } else {
                                    npcsBuilder_.addMessage(m);
                                }
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.util.List<dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc> npcs_ =
                    java.util.Collections.emptyList();

            private void ensureNpcsIsMutable() {
                if ((bitField0_ & 0x00000001) == 0) {
                    npcs_ = new java.util.ArrayList<dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc>(npcs_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.NpcOrBuilder> npcsBuilder_;

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public java.util.List<dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc> getNpcsList() {
                if (npcsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(npcs_);
                } else {
                    return npcsBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public int getNpcsCount() {
                if (npcsBuilder_ == null) {
                    return npcs_.size();
                } else {
                    return npcsBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc getNpcs(int index) {
                if (npcsBuilder_ == null) {
                    return npcs_.get(index);
                } else {
                    return npcsBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public Builder setNpcs(
                    int index, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc value) {
                if (npcsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureNpcsIsMutable();
                    npcs_.set(index, value);
                    onChanged();
                } else {
                    npcsBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public Builder setNpcs(
                    int index, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder builderForValue) {
                if (npcsBuilder_ == null) {
                    ensureNpcsIsMutable();
                    npcs_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    npcsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public Builder addNpcs(dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc value) {
                if (npcsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureNpcsIsMutable();
                    npcs_.add(value);
                    onChanged();
                } else {
                    npcsBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public Builder addNpcs(
                    int index, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc value) {
                if (npcsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureNpcsIsMutable();
                    npcs_.add(index, value);
                    onChanged();
                } else {
                    npcsBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public Builder addNpcs(
                    dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder builderForValue) {
                if (npcsBuilder_ == null) {
                    ensureNpcsIsMutable();
                    npcs_.add(builderForValue.build());
                    onChanged();
                } else {
                    npcsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public Builder addNpcs(
                    int index, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder builderForValue) {
                if (npcsBuilder_ == null) {
                    ensureNpcsIsMutable();
                    npcs_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    npcsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public Builder addAllNpcs(
                    java.lang.Iterable<? extends dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc> values) {
                if (npcsBuilder_ == null) {
                    ensureNpcsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, npcs_);
                    onChanged();
                } else {
                    npcsBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public Builder clearNpcs() {
                if (npcsBuilder_ == null) {
                    npcs_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    npcsBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public Builder removeNpcs(int index) {
                if (npcsBuilder_ == null) {
                    ensureNpcsIsMutable();
                    npcs_.remove(index);
                    onChanged();
                } else {
                    npcsBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder getNpcsBuilder(
                    int index) {
                return getNpcsFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.NpcOuterClass.NpcOrBuilder getNpcsOrBuilder(
                    int index) {
                if (npcsBuilder_ == null) {
                    return npcs_.get(index);
                } else {
                    return npcsBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public java.util.List<? extends dev.foxikle.customnpcs.internal.proto.NpcOuterClass.NpcOrBuilder>
            getNpcsOrBuilderList() {
                if (npcsBuilder_ != null) {
                    return npcsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(npcs_);
                }
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder addNpcsBuilder() {
                return getNpcsFieldBuilder().addBuilder(
                        dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.getDefaultInstance());
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder addNpcsBuilder(
                    int index) {
                return getNpcsFieldBuilder().addBuilder(
                        index, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.getDefaultInstance());
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Npc npcs = 1;</code>
             */
            public java.util.List<dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder>
            getNpcsBuilderList() {
                return getNpcsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.NpcOrBuilder>
            getNpcsFieldBuilder() {
                if (npcsBuilder_ == null) {
                    npcsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.NpcOrBuilder>(
                            npcs_,
                            ((bitField0_ & 0x00000001) != 0),
                            getParentForChildren(),
                            isClean());
                    npcs_ = null;
                }
                return npcsBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:dev.foxikle.customnpcs.internal.proto.NpcList)
        }

        // @@protoc_insertion_point(class_scope:dev.foxikle.customnpcs.internal.proto.NpcList)
        private static final dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList();
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<NpcList>
                PARSER = new com.google.protobuf.AbstractParser<NpcList>() {
            @java.lang.Override
            public NpcList parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<NpcList> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<NpcList> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.NpcListOuterClass.NpcList getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dev_foxikle_customnpcs_internal_proto_NpcList_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_dev_foxikle_customnpcs_internal_proto_NpcList_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016npc_list.proto\022%dev.foxikle.customnpcs" +
                        ".internal.proto\032\tnpc.proto\"C\n\007NpcList\0228\n" +
                        "\004npcs\030\001 \003(\0132*.dev.foxikle.customnpcs.int" +
                        "ernal.proto.Npcb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                dev.foxikle.customnpcs.internal.proto.NpcOuterClass.getDescriptor(),
                        });
        internal_static_dev_foxikle_customnpcs_internal_proto_NpcList_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_dev_foxikle_customnpcs_internal_proto_NpcList_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_dev_foxikle_customnpcs_internal_proto_NpcList_descriptor,
                new java.lang.String[]{"Npcs",});
        descriptor.resolveAllFeaturesImmutable();
        dev.foxikle.customnpcs.internal.proto.NpcOuterClass.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
