// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: npc.proto
// Protobuf Java Version: 4.28.3

package dev.foxikle.customnpcs.internal.proto;

public final class NpcOuterClass {
    private NpcOuterClass() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 28,
                /* patch= */ 3,
                /* suffix= */ "",
                NpcOuterClass.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface NpcOrBuilder extends
            // @@protoc_insertion_point(interface_extends:dev.foxikle.customnpcs.internal.proto.Npc)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * for migrations
         * </pre>
         *
         * <code>int32 schema_version = 1;</code>
         *
         * @return The schemaVersion.
         */
        int getSchemaVersion();

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
         */
        java.util.List<dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action>
        getActionsList();

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
         */
        dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action getActions(int index);

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
         */
        int getActionsCount();

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
         */
        java.util.List<? extends dev.foxikle.customnpcs.internal.proto.ActionOuterClass.ActionOrBuilder>
        getActionsOrBuilderList();

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
         */
        dev.foxikle.customnpcs.internal.proto.ActionOuterClass.ActionOrBuilder getActionsOrBuilder(
                int index);

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
         *
         * @return Whether the location field is set.
         */
        boolean hasLocation();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
         *
         * @return The location.
         */
        dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location getLocation();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
         */
        dev.foxikle.customnpcs.internal.proto.LocationOuterClass.LocationOrBuilder getLocationOrBuilder();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
         *
         * @return Whether the settings field is set.
         */
        boolean hasSettings();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
         *
         * @return The settings.
         */
        dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings getSettings();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
         */
        dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.SettingsOrBuilder getSettingsOrBuilder();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
         *
         * @return Whether the equipment field is set.
         */
        boolean hasEquipment();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
         *
         * @return The equipment.
         */
        dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment getEquipment();

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
         */
        dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.EquipmentOrBuilder getEquipmentOrBuilder();

        /**
         * <code>string uuid = 6;</code>
         *
         * @return The uuid.
         */
        java.lang.String getUuid();

        /**
         * <code>string uuid = 6;</code>
         *
         * @return The bytes for uuid.
         */
        com.google.protobuf.ByteString
        getUuidBytes();
    }

    /**
     * <pre>
     * DO NOT EVER CHANGE THE INDICIES
     * </pre>
     * <p>
     * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Npc}
     */
    public static final class Npc extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:dev.foxikle.customnpcs.internal.proto.Npc)
            NpcOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 28,
                    /* patch= */ 3,
                    /* suffix= */ "",
                    Npc.class.getName());
        }

        // Use Npc.newBuilder() to construct.
        private Npc(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Npc() {
            actions_ = java.util.Collections.emptyList();
            uuid_ = "";
        }

        public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return dev.foxikle.customnpcs.internal.proto.NpcOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Npc_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return dev.foxikle.customnpcs.internal.proto.NpcOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Npc_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.class, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder.class);
        }

        private int bitField0_;
        public static final int SCHEMA_VERSION_FIELD_NUMBER = 1;
        private int schemaVersion_ = 0;

        /**
         * <pre>
         * for migrations
         * </pre>
         *
         * <code>int32 schema_version = 1;</code>
         *
         * @return The schemaVersion.
         */
        @java.lang.Override
        public int getSchemaVersion() {
            return schemaVersion_;
        }

        public static final int ACTIONS_FIELD_NUMBER = 2;
        @SuppressWarnings("serial")
        private java.util.List<dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action> actions_;

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
         */
        @java.lang.Override
        public java.util.List<dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action> getActionsList() {
            return actions_;
        }

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
         */
        @java.lang.Override
        public java.util.List<? extends dev.foxikle.customnpcs.internal.proto.ActionOuterClass.ActionOrBuilder>
        getActionsOrBuilderList() {
            return actions_;
        }

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
         */
        @java.lang.Override
        public int getActionsCount() {
            return actions_.size();
        }

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action getActions(int index) {
            return actions_.get(index);
        }

        /**
         * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.ActionOuterClass.ActionOrBuilder getActionsOrBuilder(
                int index) {
            return actions_.get(index);
        }

        public static final int LOCATION_FIELD_NUMBER = 3;
        private dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location location_;

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
         *
         * @return Whether the location field is set.
         */
        @java.lang.Override
        public boolean hasLocation() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
         *
         * @return The location.
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location getLocation() {
            return location_ == null ? dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.getDefaultInstance() : location_;
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.LocationOuterClass.LocationOrBuilder getLocationOrBuilder() {
            return location_ == null ? dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.getDefaultInstance() : location_;
        }

        public static final int SETTINGS_FIELD_NUMBER = 4;
        private dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings settings_;

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
         *
         * @return Whether the settings field is set.
         */
        @java.lang.Override
        public boolean hasSettings() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
         *
         * @return The settings.
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings getSettings() {
            return settings_ == null ? dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.getDefaultInstance() : settings_;
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.SettingsOrBuilder getSettingsOrBuilder() {
            return settings_ == null ? dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.getDefaultInstance() : settings_;
        }

        public static final int EQUIPMENT_FIELD_NUMBER = 5;
        private dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment equipment_;

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
         *
         * @return Whether the equipment field is set.
         */
        @java.lang.Override
        public boolean hasEquipment() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
         *
         * @return The equipment.
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment getEquipment() {
            return equipment_ == null ? dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.getDefaultInstance() : equipment_;
        }

        /**
         * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
         */
        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.EquipmentOrBuilder getEquipmentOrBuilder() {
            return equipment_ == null ? dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.getDefaultInstance() : equipment_;
        }

        public static final int UUID_FIELD_NUMBER = 6;
        @SuppressWarnings("serial")
        private volatile java.lang.Object uuid_ = "";

        /**
         * <code>string uuid = 6;</code>
         *
         * @return The uuid.
         */
        @java.lang.Override
        public java.lang.String getUuid() {
            java.lang.Object ref = uuid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                uuid_ = s;
                return s;
            }
        }

        /**
         * <code>string uuid = 6;</code>
         *
         * @return The bytes for uuid.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUuidBytes() {
            java.lang.Object ref = uuid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                uuid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (schemaVersion_ != 0) {
                output.writeInt32(1, schemaVersion_);
            }
            for (int i = 0; i < actions_.size(); i++) {
                output.writeMessage(2, actions_.get(i));
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(3, getLocation());
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeMessage(4, getSettings());
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                output.writeMessage(5, getEquipment());
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 6, uuid_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (schemaVersion_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, schemaVersion_);
            }
            for (int i = 0; i < actions_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, actions_.get(i));
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getLocation());
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, getSettings());
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(5, getEquipment());
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(6, uuid_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Npc other)) {
                return super.equals(obj);
            }

            if (getSchemaVersion()
                    != other.getSchemaVersion()) return false;
            if (!getActionsList()
                    .equals(other.getActionsList())) return false;
            if (hasLocation() != other.hasLocation()) return false;
            if (hasLocation()) {
                if (!getLocation()
                        .equals(other.getLocation())) return false;
            }
            if (hasSettings() != other.hasSettings()) return false;
            if (hasSettings()) {
                if (!getSettings()
                        .equals(other.getSettings())) return false;
            }
            if (hasEquipment() != other.hasEquipment()) return false;
            if (hasEquipment()) {
                if (!getEquipment()
                        .equals(other.getEquipment())) return false;
            }
            if (!getUuid()
                    .equals(other.getUuid())) return false;
            return getUnknownFields().equals(other.getUnknownFields());
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SCHEMA_VERSION_FIELD_NUMBER;
            hash = (53 * hash) + getSchemaVersion();
            if (getActionsCount() > 0) {
                hash = (37 * hash) + ACTIONS_FIELD_NUMBER;
                hash = (53 * hash) + getActionsList().hashCode();
            }
            if (hasLocation()) {
                hash = (37 * hash) + LOCATION_FIELD_NUMBER;
                hash = (53 * hash) + getLocation().hashCode();
            }
            if (hasSettings()) {
                hash = (37 * hash) + SETTINGS_FIELD_NUMBER;
                hash = (53 * hash) + getSettings().hashCode();
            }
            if (hasEquipment()) {
                hash = (37 * hash) + EQUIPMENT_FIELD_NUMBER;
                hash = (53 * hash) + getEquipment().hashCode();
            }
            hash = (37 * hash) + UUID_FIELD_NUMBER;
            hash = (53 * hash) + getUuid().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * DO NOT EVER CHANGE THE INDICIES
         * </pre>
         * <p>
         * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Npc}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:dev.foxikle.customnpcs.internal.proto.Npc)
                dev.foxikle.customnpcs.internal.proto.NpcOuterClass.NpcOrBuilder {
            public static com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return dev.foxikle.customnpcs.internal.proto.NpcOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Npc_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return dev.foxikle.customnpcs.internal.proto.NpcOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Npc_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.class, dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.Builder.class);
            }

            // Construct using dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage
                        .alwaysUseFieldBuilders) {
                    getActionsFieldBuilder();
                    getLocationFieldBuilder();
                    getSettingsFieldBuilder();
                    getEquipmentFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                schemaVersion_ = 0;
                if (actionsBuilder_ == null) {
                    actions_ = java.util.Collections.emptyList();
                } else {
                    actions_ = null;
                    actionsBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000002);
                location_ = null;
                if (locationBuilder_ != null) {
                    locationBuilder_.dispose();
                    locationBuilder_ = null;
                }
                settings_ = null;
                if (settingsBuilder_ != null) {
                    settingsBuilder_.dispose();
                    settingsBuilder_ = null;
                }
                equipment_ = null;
                if (equipmentBuilder_ != null) {
                    equipmentBuilder_.dispose();
                    equipmentBuilder_ = null;
                }
                uuid_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return dev.foxikle.customnpcs.internal.proto.NpcOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Npc_descriptor;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc getDefaultInstanceForType() {
                return dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.getDefaultInstance();
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc build() {
                dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc buildPartial() {
                dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc result = new dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc(this);
                buildPartialRepeatedFields(result);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartialRepeatedFields(dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc result) {
                if (actionsBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) != 0)) {
                        actions_ = java.util.Collections.unmodifiableList(actions_);
                        bitField0_ = (bitField0_ & ~0x00000002);
                    }
                    result.actions_ = actions_;
                } else {
                    result.actions_ = actionsBuilder_.build();
                }
            }

            private void buildPartial0(dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.schemaVersion_ = schemaVersion_;
                }
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.location_ = locationBuilder_ == null
                            ? location_
                            : locationBuilder_.build();
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.settings_ = settingsBuilder_ == null
                            ? settings_
                            : settingsBuilder_.build();
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.equipment_ = equipmentBuilder_ == null
                            ? equipment_
                            : equipmentBuilder_.build();
                    to_bitField0_ |= 0x00000004;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.uuid_ = uuid_;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc) {
                    return mergeFrom((dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc other) {
                if (other == dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc.getDefaultInstance()) return this;
                if (other.getSchemaVersion() != 0) {
                    setSchemaVersion(other.getSchemaVersion());
                }
                if (actionsBuilder_ == null) {
                    if (!other.actions_.isEmpty()) {
                        if (actions_.isEmpty()) {
                            actions_ = other.actions_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                        } else {
                            ensureActionsIsMutable();
                            actions_.addAll(other.actions_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.actions_.isEmpty()) {
                        if (actionsBuilder_.isEmpty()) {
                            actionsBuilder_.dispose();
                            actionsBuilder_ = null;
                            actions_ = other.actions_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                            actionsBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getActionsFieldBuilder() : null;
                        } else {
                            actionsBuilder_.addAllMessages(other.actions_);
                        }
                    }
                }
                if (other.hasLocation()) {
                    mergeLocation(other.getLocation());
                }
                if (other.hasSettings()) {
                    mergeSettings(other.getSettings());
                }
                if (other.hasEquipment()) {
                    mergeEquipment(other.getEquipment());
                }
                if (!other.getUuid().isEmpty()) {
                    uuid_ = other.uuid_;
                    bitField0_ |= 0x00000020;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                schemaVersion_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action m =
                                        input.readMessage(
                                                dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.parser(),
                                                extensionRegistry);
                                if (actionsBuilder_ == null) {
                                    ensureActionsIsMutable();
                                    actions_.add(m);
                                } else {
                                    actionsBuilder_.addMessage(m);
                                }
                                break;
                            } // case 18
                            case 26: {
                                input.readMessage(
                                        getLocationFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 34: {
                                input.readMessage(
                                        getSettingsFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 34
                            case 42: {
                                input.readMessage(
                                        getEquipmentFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 42
                            case 50: {
                                uuid_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 50
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private int schemaVersion_;

            /**
             * <pre>
             * for migrations
             * </pre>
             *
             * <code>int32 schema_version = 1;</code>
             *
             * @return The schemaVersion.
             */
            @java.lang.Override
            public int getSchemaVersion() {
                return schemaVersion_;
            }

            /**
             * <pre>
             * for migrations
             * </pre>
             *
             * <code>int32 schema_version = 1;</code>
             *
             * @param value The schemaVersion to set.
             * @return This builder for chaining.
             */
            public Builder setSchemaVersion(int value) {

                schemaVersion_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * for migrations
             * </pre>
             *
             * <code>int32 schema_version = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSchemaVersion() {
                bitField0_ = (bitField0_ & ~0x00000001);
                schemaVersion_ = 0;
                onChanged();
                return this;
            }

            private java.util.List<dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action> actions_ =
                    java.util.Collections.emptyList();

            private void ensureActionsIsMutable() {
                if ((bitField0_ & 0x00000002) == 0) {
                    actions_ = new java.util.ArrayList<dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action>(actions_);
                    bitField0_ |= 0x00000002;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.ActionOrBuilder> actionsBuilder_;

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public java.util.List<dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action> getActionsList() {
                if (actionsBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(actions_);
                } else {
                    return actionsBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public int getActionsCount() {
                if (actionsBuilder_ == null) {
                    return actions_.size();
                } else {
                    return actionsBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action getActions(int index) {
                if (actionsBuilder_ == null) {
                    return actions_.get(index);
                } else {
                    return actionsBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public Builder setActions(
                    int index, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action value) {
                if (actionsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureActionsIsMutable();
                    actions_.set(index, value);
                    onChanged();
                } else {
                    actionsBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public Builder setActions(
                    int index, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder builderForValue) {
                if (actionsBuilder_ == null) {
                    ensureActionsIsMutable();
                    actions_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    actionsBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public Builder addActions(dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action value) {
                if (actionsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureActionsIsMutable();
                    actions_.add(value);
                    onChanged();
                } else {
                    actionsBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public Builder addActions(
                    int index, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action value) {
                if (actionsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureActionsIsMutable();
                    actions_.add(index, value);
                    onChanged();
                } else {
                    actionsBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public Builder addActions(
                    dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder builderForValue) {
                if (actionsBuilder_ == null) {
                    ensureActionsIsMutable();
                    actions_.add(builderForValue.build());
                    onChanged();
                } else {
                    actionsBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public Builder addActions(
                    int index, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder builderForValue) {
                if (actionsBuilder_ == null) {
                    ensureActionsIsMutable();
                    actions_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    actionsBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public Builder addAllActions(
                    java.lang.Iterable<? extends dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action> values) {
                if (actionsBuilder_ == null) {
                    ensureActionsIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, actions_);
                    onChanged();
                } else {
                    actionsBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public Builder clearActions() {
                if (actionsBuilder_ == null) {
                    actions_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                    onChanged();
                } else {
                    actionsBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public Builder removeActions(int index) {
                if (actionsBuilder_ == null) {
                    ensureActionsIsMutable();
                    actions_.remove(index);
                    onChanged();
                } else {
                    actionsBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder getActionsBuilder(
                    int index) {
                return getActionsFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ActionOuterClass.ActionOrBuilder getActionsOrBuilder(
                    int index) {
                if (actionsBuilder_ == null) {
                    return actions_.get(index);
                } else {
                    return actionsBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public java.util.List<? extends dev.foxikle.customnpcs.internal.proto.ActionOuterClass.ActionOrBuilder>
            getActionsOrBuilderList() {
                if (actionsBuilder_ != null) {
                    return actionsBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(actions_);
                }
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder addActionsBuilder() {
                return getActionsFieldBuilder().addBuilder(
                        dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.getDefaultInstance());
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder addActionsBuilder(
                    int index) {
                return getActionsFieldBuilder().addBuilder(
                        index, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.getDefaultInstance());
            }

            /**
             * <code>repeated .dev.foxikle.customnpcs.internal.proto.Action actions = 2;</code>
             */
            public java.util.List<dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder>
            getActionsBuilderList() {
                return getActionsFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.ActionOrBuilder>
            getActionsFieldBuilder() {
                if (actionsBuilder_ == null) {
                    actionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.Action.Builder, dev.foxikle.customnpcs.internal.proto.ActionOuterClass.ActionOrBuilder>(
                            actions_,
                            ((bitField0_ & 0x00000002) != 0),
                            getParentForChildren(),
                            isClean());
                    actions_ = null;
                }
                return actionsBuilder_;
            }

            private dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location location_;
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location, dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.Builder, dev.foxikle.customnpcs.internal.proto.LocationOuterClass.LocationOrBuilder> locationBuilder_;

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
             *
             * @return Whether the location field is set.
             */
            public boolean hasLocation() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
             *
             * @return The location.
             */
            public dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location getLocation() {
                if (locationBuilder_ == null) {
                    return location_ == null ? dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.getDefaultInstance() : location_;
                } else {
                    return locationBuilder_.getMessage();
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
             */
            public Builder setLocation(dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location value) {
                if (locationBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    location_ = value;
                } else {
                    locationBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
             */
            public Builder setLocation(
                    dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.Builder builderForValue) {
                if (locationBuilder_ == null) {
                    location_ = builderForValue.build();
                } else {
                    locationBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
             */
            public Builder mergeLocation(dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location value) {
                if (locationBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) != 0) &&
                            location_ != null &&
                            location_ != dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.getDefaultInstance()) {
                        getLocationBuilder().mergeFrom(value);
                    } else {
                        location_ = value;
                    }
                } else {
                    locationBuilder_.mergeFrom(value);
                }
                if (location_ != null) {
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
             */
            public Builder clearLocation() {
                bitField0_ = (bitField0_ & ~0x00000004);
                location_ = null;
                if (locationBuilder_ != null) {
                    locationBuilder_.dispose();
                    locationBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.Builder getLocationBuilder() {
                bitField0_ |= 0x00000004;
                onChanged();
                return getLocationFieldBuilder().getBuilder();
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.LocationOuterClass.LocationOrBuilder getLocationOrBuilder() {
                if (locationBuilder_ != null) {
                    return locationBuilder_.getMessageOrBuilder();
                } else {
                    return location_ == null ?
                            dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.getDefaultInstance() : location_;
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Location location = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location, dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.Builder, dev.foxikle.customnpcs.internal.proto.LocationOuterClass.LocationOrBuilder>
            getLocationFieldBuilder() {
                if (locationBuilder_ == null) {
                    locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location, dev.foxikle.customnpcs.internal.proto.LocationOuterClass.Location.Builder, dev.foxikle.customnpcs.internal.proto.LocationOuterClass.LocationOrBuilder>(
                            getLocation(),
                            getParentForChildren(),
                            isClean());
                    location_ = null;
                }
                return locationBuilder_;
            }

            private dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings settings_;
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings, dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.Builder, dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.SettingsOrBuilder> settingsBuilder_;

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
             *
             * @return Whether the settings field is set.
             */
            public boolean hasSettings() {
                return ((bitField0_ & 0x00000008) != 0);
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
             *
             * @return The settings.
             */
            public dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings getSettings() {
                if (settingsBuilder_ == null) {
                    return settings_ == null ? dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.getDefaultInstance() : settings_;
                } else {
                    return settingsBuilder_.getMessage();
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
             */
            public Builder setSettings(dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings value) {
                if (settingsBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    settings_ = value;
                } else {
                    settingsBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
             */
            public Builder setSettings(
                    dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.Builder builderForValue) {
                if (settingsBuilder_ == null) {
                    settings_ = builderForValue.build();
                } else {
                    settingsBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
             */
            public Builder mergeSettings(dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings value) {
                if (settingsBuilder_ == null) {
                    if (((bitField0_ & 0x00000008) != 0) &&
                            settings_ != null &&
                            settings_ != dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.getDefaultInstance()) {
                        getSettingsBuilder().mergeFrom(value);
                    } else {
                        settings_ = value;
                    }
                } else {
                    settingsBuilder_.mergeFrom(value);
                }
                if (settings_ != null) {
                    bitField0_ |= 0x00000008;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
             */
            public Builder clearSettings() {
                bitField0_ = (bitField0_ & ~0x00000008);
                settings_ = null;
                if (settingsBuilder_ != null) {
                    settingsBuilder_.dispose();
                    settingsBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.Builder getSettingsBuilder() {
                bitField0_ |= 0x00000008;
                onChanged();
                return getSettingsFieldBuilder().getBuilder();
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.SettingsOrBuilder getSettingsOrBuilder() {
                if (settingsBuilder_ != null) {
                    return settingsBuilder_.getMessageOrBuilder();
                } else {
                    return settings_ == null ?
                            dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.getDefaultInstance() : settings_;
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Settings settings = 4;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings, dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.Builder, dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.SettingsOrBuilder>
            getSettingsFieldBuilder() {
                if (settingsBuilder_ == null) {
                    settingsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings, dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.Builder, dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.SettingsOrBuilder>(
                            getSettings(),
                            getParentForChildren(),
                            isClean());
                    settings_ = null;
                }
                return settingsBuilder_;
            }

            private dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment equipment_;
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment, dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.Builder, dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.EquipmentOrBuilder> equipmentBuilder_;

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
             *
             * @return Whether the equipment field is set.
             */
            public boolean hasEquipment() {
                return ((bitField0_ & 0x00000010) != 0);
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
             *
             * @return The equipment.
             */
            public dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment getEquipment() {
                if (equipmentBuilder_ == null) {
                    return equipment_ == null ? dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.getDefaultInstance() : equipment_;
                } else {
                    return equipmentBuilder_.getMessage();
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
             */
            public Builder setEquipment(dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment value) {
                if (equipmentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    equipment_ = value;
                } else {
                    equipmentBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
             */
            public Builder setEquipment(
                    dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.Builder builderForValue) {
                if (equipmentBuilder_ == null) {
                    equipment_ = builderForValue.build();
                } else {
                    equipmentBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
             */
            public Builder mergeEquipment(dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment value) {
                if (equipmentBuilder_ == null) {
                    if (((bitField0_ & 0x00000010) != 0) &&
                            equipment_ != null &&
                            equipment_ != dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.getDefaultInstance()) {
                        getEquipmentBuilder().mergeFrom(value);
                    } else {
                        equipment_ = value;
                    }
                } else {
                    equipmentBuilder_.mergeFrom(value);
                }
                if (equipment_ != null) {
                    bitField0_ |= 0x00000010;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
             */
            public Builder clearEquipment() {
                bitField0_ = (bitField0_ & ~0x00000010);
                equipment_ = null;
                if (equipmentBuilder_ != null) {
                    equipmentBuilder_.dispose();
                    equipmentBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.Builder getEquipmentBuilder() {
                bitField0_ |= 0x00000010;
                onChanged();
                return getEquipmentFieldBuilder().getBuilder();
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
             */
            public dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.EquipmentOrBuilder getEquipmentOrBuilder() {
                if (equipmentBuilder_ != null) {
                    return equipmentBuilder_.getMessageOrBuilder();
                } else {
                    return equipment_ == null ?
                            dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.getDefaultInstance() : equipment_;
                }
            }

            /**
             * <code>.dev.foxikle.customnpcs.internal.proto.Equipment equipment = 5;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment, dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.Builder, dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.EquipmentOrBuilder>
            getEquipmentFieldBuilder() {
                if (equipmentBuilder_ == null) {
                    equipmentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment, dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.Equipment.Builder, dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.EquipmentOrBuilder>(
                            getEquipment(),
                            getParentForChildren(),
                            isClean());
                    equipment_ = null;
                }
                return equipmentBuilder_;
            }

            private java.lang.Object uuid_ = "";

            /**
             * <code>string uuid = 6;</code>
             *
             * @return The uuid.
             */
            public java.lang.String getUuid() {
                java.lang.Object ref = uuid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    uuid_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string uuid = 6;</code>
             *
             * @return The bytes for uuid.
             */
            public com.google.protobuf.ByteString
            getUuidBytes() {
                java.lang.Object ref = uuid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    uuid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string uuid = 6;</code>
             *
             * @param value The uuid to set.
             * @return This builder for chaining.
             */
            public Builder setUuid(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                uuid_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <code>string uuid = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUuid() {
                uuid_ = getDefaultInstance().getUuid();
                bitField0_ = (bitField0_ & ~0x00000020);
                onChanged();
                return this;
            }

            /**
             * <code>string uuid = 6;</code>
             *
             * @param value The bytes for uuid to set.
             * @return This builder for chaining.
             */
            public Builder setUuidBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                uuid_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:dev.foxikle.customnpcs.internal.proto.Npc)
        }

        // @@protoc_insertion_point(class_scope:dev.foxikle.customnpcs.internal.proto.Npc)
        private static final dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc();
        }

        public static dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Npc>
                PARSER = new com.google.protobuf.AbstractParser<Npc>() {
            @java.lang.Override
            public Npc parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Npc> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Npc> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.NpcOuterClass.Npc getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dev_foxikle_customnpcs_internal_proto_Npc_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_dev_foxikle_customnpcs_internal_proto_Npc_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\tnpc.proto\022%dev.foxikle.customnpcs.inte" +
                        "rnal.proto\032\014action.proto\032\016location.proto" +
                        "\032\017equipment.proto\032\016settings.proto\"\266\002\n\003Np" +
                        "c\022\026\n\016schema_version\030\001 \001(\005\022>\n\007actions\030\002 \003" +
                        "(\0132-.dev.foxikle.customnpcs.internal.pro" +
                        "to.Action\022A\n\010location\030\003 \001(\0132/.dev.foxikl" +
                        "e.customnpcs.internal.proto.Location\022A\n\010" +
                        "settings\030\004 \001(\0132/.dev.foxikle.customnpcs." +
                        "internal.proto.Settings\022C\n\tequipment\030\005 \001" +
                        "(\01320.dev.foxikle.customnpcs.internal.pro" +
                        "to.Equipment\022\014\n\004uuid\030\006 \001(\tb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                dev.foxikle.customnpcs.internal.proto.ActionOuterClass.getDescriptor(),
                                dev.foxikle.customnpcs.internal.proto.LocationOuterClass.getDescriptor(),
                                dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.getDescriptor(),
                                dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.getDescriptor(),
                        });
        internal_static_dev_foxikle_customnpcs_internal_proto_Npc_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_dev_foxikle_customnpcs_internal_proto_Npc_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_dev_foxikle_customnpcs_internal_proto_Npc_descriptor,
                new java.lang.String[]{"SchemaVersion", "Actions", "Location", "Settings", "Equipment", "Uuid",});
        descriptor.resolveAllFeaturesImmutable();
        dev.foxikle.customnpcs.internal.proto.ActionOuterClass.getDescriptor();
        dev.foxikle.customnpcs.internal.proto.LocationOuterClass.getDescriptor();
        dev.foxikle.customnpcs.internal.proto.EquipmentOuterClass.getDescriptor();
        dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
