// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: settings.proto
// Protobuf Java Version: 4.28.3

package dev.foxikle.customnpcs.internal.proto;

public final class SettingsOuterClass {
    private SettingsOuterClass() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 28,
                /* patch= */ 3,
                /* suffix= */ "",
                SettingsOuterClass.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface SettingsOrBuilder extends
            // @@protoc_insertion_point(interface_extends:dev.foxikle.customnpcs.internal.proto.Settings)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 schema_version = 1;</code>
         *
         * @return The schemaVersion.
         */
        int getSchemaVersion();

        /**
         * <code>string value = 2;</code>
         *
         * @return The value.
         */
        java.lang.String getValue();

        /**
         * <code>string value = 2;</code>
         *
         * @return The bytes for value.
         */
        com.google.protobuf.ByteString
        getValueBytes();

        /**
         * <code>string signature = 3;</code>
         *
         * @return The signature.
         */
        java.lang.String getSignature();

        /**
         * <code>string signature = 3;</code>
         *
         * @return The bytes for signature.
         */
        com.google.protobuf.ByteString
        getSignatureBytes();

        /**
         * <code>string skin_name = 4;</code>
         *
         * @return The skinName.
         */
        java.lang.String getSkinName();

        /**
         * <code>string skin_name = 4;</code>
         *
         * @return The bytes for skinName.
         */
        com.google.protobuf.ByteString
        getSkinNameBytes();

        /**
         * <code>string custom_hologram = 5;</code>
         *
         * @return The customHologram.
         */
        java.lang.String getCustomHologram();

        /**
         * <code>string custom_hologram = 5;</code>
         *
         * @return The bytes for customHologram.
         */
        com.google.protobuf.ByteString
        getCustomHologramBytes();

        /**
         * <code>string name = 6;</code>
         *
         * @return The name.
         */
        java.lang.String getName();

        /**
         * <code>string name = 6;</code>
         *
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>bool clickable = 7;</code>
         *
         * @return The clickable.
         */
        boolean getClickable();

        /**
         * <code>bool hide_click_hologram = 8;</code>
         *
         * @return The hideClickHologram.
         */
        boolean getHideClickHologram();

        /**
         * <code>bool tunnel_vision = 9;</code>
         *
         * @return The tunnelVision.
         */
        boolean getTunnelVision();

        /**
         * <code>bool resilient = 10;</code>
         *
         * @return The resilient.
         */
        boolean getResilient();
    }

    /**
     * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Settings}
     */
    public static final class Settings extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:dev.foxikle.customnpcs.internal.proto.Settings)
            SettingsOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 28,
                    /* patch= */ 3,
                    /* suffix= */ "",
                    Settings.class.getName());
        }

        // Use Settings.newBuilder() to construct.
        private Settings(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Settings() {
            value_ = "";
            signature_ = "";
            skinName_ = "";
            customHologram_ = "";
            name_ = "";
        }

        public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Settings_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Settings_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.class, dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.Builder.class);
        }

        public static final int SCHEMA_VERSION_FIELD_NUMBER = 1;
        private int schemaVersion_ = 0;

        /**
         * <code>int32 schema_version = 1;</code>
         *
         * @return The schemaVersion.
         */
        @java.lang.Override
        public int getSchemaVersion() {
            return schemaVersion_;
        }

        public static final int VALUE_FIELD_NUMBER = 2;
        @SuppressWarnings("serial")
        private volatile java.lang.Object value_ = "";

        /**
         * <code>string value = 2;</code>
         *
         * @return The value.
         */
        @java.lang.Override
        public java.lang.String getValue() {
            java.lang.Object ref = value_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                value_ = s;
                return s;
            }
        }

        /**
         * <code>string value = 2;</code>
         *
         * @return The bytes for value.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getValueBytes() {
            java.lang.Object ref = value_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                value_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SIGNATURE_FIELD_NUMBER = 3;
        @SuppressWarnings("serial")
        private volatile java.lang.Object signature_ = "";

        /**
         * <code>string signature = 3;</code>
         *
         * @return The signature.
         */
        @java.lang.Override
        public java.lang.String getSignature() {
            java.lang.Object ref = signature_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                signature_ = s;
                return s;
            }
        }

        /**
         * <code>string signature = 3;</code>
         *
         * @return The bytes for signature.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getSignatureBytes() {
            java.lang.Object ref = signature_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                signature_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SKIN_NAME_FIELD_NUMBER = 4;
        @SuppressWarnings("serial")
        private volatile java.lang.Object skinName_ = "";

        /**
         * <code>string skin_name = 4;</code>
         *
         * @return The skinName.
         */
        @java.lang.Override
        public java.lang.String getSkinName() {
            java.lang.Object ref = skinName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                skinName_ = s;
                return s;
            }
        }

        /**
         * <code>string skin_name = 4;</code>
         *
         * @return The bytes for skinName.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getSkinNameBytes() {
            java.lang.Object ref = skinName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                skinName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CUSTOM_HOLOGRAM_FIELD_NUMBER = 5;
        @SuppressWarnings("serial")
        private volatile java.lang.Object customHologram_ = "";

        /**
         * <code>string custom_hologram = 5;</code>
         *
         * @return The customHologram.
         */
        @java.lang.Override
        public java.lang.String getCustomHologram() {
            java.lang.Object ref = customHologram_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                customHologram_ = s;
                return s;
            }
        }

        /**
         * <code>string custom_hologram = 5;</code>
         *
         * @return The bytes for customHologram.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getCustomHologramBytes() {
            java.lang.Object ref = customHologram_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                customHologram_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int NAME_FIELD_NUMBER = 6;
        @SuppressWarnings("serial")
        private volatile java.lang.Object name_ = "";

        /**
         * <code>string name = 6;</code>
         *
         * @return The name.
         */
        @java.lang.Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 6;</code>
         *
         * @return The bytes for name.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CLICKABLE_FIELD_NUMBER = 7;
        private boolean clickable_ = false;

        /**
         * <code>bool clickable = 7;</code>
         *
         * @return The clickable.
         */
        @java.lang.Override
        public boolean getClickable() {
            return clickable_;
        }

        public static final int HIDE_CLICK_HOLOGRAM_FIELD_NUMBER = 8;
        private boolean hideClickHologram_ = false;

        /**
         * <code>bool hide_click_hologram = 8;</code>
         *
         * @return The hideClickHologram.
         */
        @java.lang.Override
        public boolean getHideClickHologram() {
            return hideClickHologram_;
        }

        public static final int TUNNEL_VISION_FIELD_NUMBER = 9;
        private boolean tunnelVision_ = false;

        /**
         * <code>bool tunnel_vision = 9;</code>
         *
         * @return The tunnelVision.
         */
        @java.lang.Override
        public boolean getTunnelVision() {
            return tunnelVision_;
        }

        public static final int RESILIENT_FIELD_NUMBER = 10;
        private boolean resilient_ = false;

        /**
         * <code>bool resilient = 10;</code>
         *
         * @return The resilient.
         */
        @java.lang.Override
        public boolean getResilient() {
            return resilient_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (schemaVersion_ != 0) {
                output.writeInt32(1, schemaVersion_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 2, value_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(signature_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, signature_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(skinName_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 4, skinName_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(customHologram_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 5, customHologram_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 6, name_);
            }
            if (clickable_) {
                output.writeBool(7, clickable_);
            }
            if (hideClickHologram_) {
                output.writeBool(8, hideClickHologram_);
            }
            if (tunnelVision_) {
                output.writeBool(9, tunnelVision_);
            }
            if (resilient_) {
                output.writeBool(10, resilient_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (schemaVersion_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, schemaVersion_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(2, value_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(signature_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, signature_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(skinName_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(4, skinName_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(customHologram_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(5, customHologram_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(6, name_);
            }
            if (clickable_) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(7, clickable_);
            }
            if (hideClickHologram_) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(8, hideClickHologram_);
            }
            if (tunnelVision_) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(9, tunnelVision_);
            }
            if (resilient_) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(10, resilient_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Settings other)) {
                return super.equals(obj);
            }

            if (getSchemaVersion()
                    != other.getSchemaVersion()) return false;
            if (!getValue()
                    .equals(other.getValue())) return false;
            if (!getSignature()
                    .equals(other.getSignature())) return false;
            if (!getSkinName()
                    .equals(other.getSkinName())) return false;
            if (!getCustomHologram()
                    .equals(other.getCustomHologram())) return false;
            if (!getName()
                    .equals(other.getName())) return false;
            if (getClickable()
                    != other.getClickable()) return false;
            if (getHideClickHologram()
                    != other.getHideClickHologram()) return false;
            if (getTunnelVision()
                    != other.getTunnelVision()) return false;
            if (getResilient()
                    != other.getResilient()) return false;
            return getUnknownFields().equals(other.getUnknownFields());
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SCHEMA_VERSION_FIELD_NUMBER;
            hash = (53 * hash) + getSchemaVersion();
            hash = (37 * hash) + VALUE_FIELD_NUMBER;
            hash = (53 * hash) + getValue().hashCode();
            hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
            hash = (53 * hash) + getSignature().hashCode();
            hash = (37 * hash) + SKIN_NAME_FIELD_NUMBER;
            hash = (53 * hash) + getSkinName().hashCode();
            hash = (37 * hash) + CUSTOM_HOLOGRAM_FIELD_NUMBER;
            hash = (53 * hash) + getCustomHologram().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + CLICKABLE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getClickable());
            hash = (37 * hash) + HIDE_CLICK_HOLOGRAM_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getHideClickHologram());
            hash = (37 * hash) + TUNNEL_VISION_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getTunnelVision());
            hash = (37 * hash) + RESILIENT_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getResilient());
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code dev.foxikle.customnpcs.internal.proto.Settings}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:dev.foxikle.customnpcs.internal.proto.Settings)
                dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.SettingsOrBuilder {
            public static com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Settings_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Settings_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.class, dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.Builder.class);
            }

            // Construct using dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                schemaVersion_ = 0;
                value_ = "";
                signature_ = "";
                skinName_ = "";
                customHologram_ = "";
                name_ = "";
                clickable_ = false;
                hideClickHologram_ = false;
                tunnelVision_ = false;
                resilient_ = false;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.internal_static_dev_foxikle_customnpcs_internal_proto_Settings_descriptor;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings getDefaultInstanceForType() {
                return dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.getDefaultInstance();
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings build() {
                dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings buildPartial() {
                dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings result = new dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.schemaVersion_ = schemaVersion_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.value_ = value_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.signature_ = signature_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.skinName_ = skinName_;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.customHologram_ = customHologram_;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.name_ = name_;
                }
                if (((from_bitField0_ & 0x00000040) != 0)) {
                    result.clickable_ = clickable_;
                }
                if (((from_bitField0_ & 0x00000080) != 0)) {
                    result.hideClickHologram_ = hideClickHologram_;
                }
                if (((from_bitField0_ & 0x00000100) != 0)) {
                    result.tunnelVision_ = tunnelVision_;
                }
                if (((from_bitField0_ & 0x00000200) != 0)) {
                    result.resilient_ = resilient_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings) {
                    return mergeFrom((dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings other) {
                if (other == dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings.getDefaultInstance())
                    return this;
                if (other.getSchemaVersion() != 0) {
                    setSchemaVersion(other.getSchemaVersion());
                }
                if (!other.getValue().isEmpty()) {
                    value_ = other.value_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                if (!other.getSignature().isEmpty()) {
                    signature_ = other.signature_;
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                if (!other.getSkinName().isEmpty()) {
                    skinName_ = other.skinName_;
                    bitField0_ |= 0x00000008;
                    onChanged();
                }
                if (!other.getCustomHologram().isEmpty()) {
                    customHologram_ = other.customHologram_;
                    bitField0_ |= 0x00000010;
                    onChanged();
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    bitField0_ |= 0x00000020;
                    onChanged();
                }
                if (other.getClickable()) {
                    setClickable(other.getClickable());
                }
                if (other.getHideClickHologram()) {
                    setHideClickHologram(other.getHideClickHologram());
                }
                if (other.getTunnelVision()) {
                    setTunnelVision(other.getTunnelVision());
                }
                if (other.getResilient()) {
                    setResilient(other.getResilient());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                schemaVersion_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                value_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26: {
                                signature_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 34: {
                                skinName_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 34
                            case 42: {
                                customHologram_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 42
                            case 50: {
                                name_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 50
                            case 56: {
                                clickable_ = input.readBool();
                                bitField0_ |= 0x00000040;
                                break;
                            } // case 56
                            case 64: {
                                hideClickHologram_ = input.readBool();
                                bitField0_ |= 0x00000080;
                                break;
                            } // case 64
                            case 72: {
                                tunnelVision_ = input.readBool();
                                bitField0_ |= 0x00000100;
                                break;
                            } // case 72
                            case 80: {
                                resilient_ = input.readBool();
                                bitField0_ |= 0x00000200;
                                break;
                            } // case 80
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private int schemaVersion_;

            /**
             * <code>int32 schema_version = 1;</code>
             *
             * @return The schemaVersion.
             */
            @java.lang.Override
            public int getSchemaVersion() {
                return schemaVersion_;
            }

            /**
             * <code>int32 schema_version = 1;</code>
             *
             * @param value The schemaVersion to set.
             * @return This builder for chaining.
             */
            public Builder setSchemaVersion(int value) {

                schemaVersion_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>int32 schema_version = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSchemaVersion() {
                bitField0_ = (bitField0_ & ~0x00000001);
                schemaVersion_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object value_ = "";

            /**
             * <code>string value = 2;</code>
             *
             * @return The value.
             */
            public java.lang.String getValue() {
                java.lang.Object ref = value_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    value_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string value = 2;</code>
             *
             * @return The bytes for value.
             */
            public com.google.protobuf.ByteString
            getValueBytes() {
                java.lang.Object ref = value_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    value_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string value = 2;</code>
             *
             * @param value The value to set.
             * @return This builder for chaining.
             */
            public Builder setValue(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                value_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string value = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearValue() {
                value_ = getDefaultInstance().getValue();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <code>string value = 2;</code>
             *
             * @param value The bytes for value to set.
             * @return This builder for chaining.
             */
            public Builder setValueBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                value_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            private java.lang.Object signature_ = "";

            /**
             * <code>string signature = 3;</code>
             *
             * @return The signature.
             */
            public java.lang.String getSignature() {
                java.lang.Object ref = signature_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    signature_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string signature = 3;</code>
             *
             * @return The bytes for signature.
             */
            public com.google.protobuf.ByteString
            getSignatureBytes() {
                java.lang.Object ref = signature_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    signature_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string signature = 3;</code>
             *
             * @param value The signature to set.
             * @return This builder for chaining.
             */
            public Builder setSignature(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                signature_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>string signature = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSignature() {
                signature_ = getDefaultInstance().getSignature();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            /**
             * <code>string signature = 3;</code>
             *
             * @param value The bytes for signature to set.
             * @return This builder for chaining.
             */
            public Builder setSignatureBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                signature_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            private java.lang.Object skinName_ = "";

            /**
             * <code>string skin_name = 4;</code>
             *
             * @return The skinName.
             */
            public java.lang.String getSkinName() {
                java.lang.Object ref = skinName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    skinName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string skin_name = 4;</code>
             *
             * @return The bytes for skinName.
             */
            public com.google.protobuf.ByteString
            getSkinNameBytes() {
                java.lang.Object ref = skinName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    skinName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string skin_name = 4;</code>
             *
             * @param value The skinName to set.
             * @return This builder for chaining.
             */
            public Builder setSkinName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                skinName_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>string skin_name = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSkinName() {
                skinName_ = getDefaultInstance().getSkinName();
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }

            /**
             * <code>string skin_name = 4;</code>
             *
             * @param value The bytes for skinName to set.
             * @return This builder for chaining.
             */
            public Builder setSkinNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                skinName_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            private java.lang.Object customHologram_ = "";

            /**
             * <code>string custom_hologram = 5;</code>
             *
             * @return The customHologram.
             */
            public java.lang.String getCustomHologram() {
                java.lang.Object ref = customHologram_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    customHologram_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string custom_hologram = 5;</code>
             *
             * @return The bytes for customHologram.
             */
            public com.google.protobuf.ByteString
            getCustomHologramBytes() {
                java.lang.Object ref = customHologram_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    customHologram_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string custom_hologram = 5;</code>
             *
             * @param value The customHologram to set.
             * @return This builder for chaining.
             */
            public Builder setCustomHologram(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                customHologram_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>string custom_hologram = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCustomHologram() {
                customHologram_ = getDefaultInstance().getCustomHologram();
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
                return this;
            }

            /**
             * <code>string custom_hologram = 5;</code>
             *
             * @param value The bytes for customHologram to set.
             * @return This builder for chaining.
             */
            public Builder setCustomHologramBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                customHologram_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <code>string name = 6;</code>
             *
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string name = 6;</code>
             *
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 6;</code>
             *
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                name_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearName() {
                name_ = getDefaultInstance().getName();
                bitField0_ = (bitField0_ & ~0x00000020);
                onChanged();
                return this;
            }

            /**
             * <code>string name = 6;</code>
             *
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                name_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            private boolean clickable_;

            /**
             * <code>bool clickable = 7;</code>
             *
             * @return The clickable.
             */
            @java.lang.Override
            public boolean getClickable() {
                return clickable_;
            }

            /**
             * <code>bool clickable = 7;</code>
             *
             * @param value The clickable to set.
             * @return This builder for chaining.
             */
            public Builder setClickable(boolean value) {

                clickable_ = value;
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            /**
             * <code>bool clickable = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearClickable() {
                bitField0_ = (bitField0_ & ~0x00000040);
                clickable_ = false;
                onChanged();
                return this;
            }

            private boolean hideClickHologram_;

            /**
             * <code>bool hide_click_hologram = 8;</code>
             *
             * @return The hideClickHologram.
             */
            @java.lang.Override
            public boolean getHideClickHologram() {
                return hideClickHologram_;
            }

            /**
             * <code>bool hide_click_hologram = 8;</code>
             *
             * @param value The hideClickHologram to set.
             * @return This builder for chaining.
             */
            public Builder setHideClickHologram(boolean value) {

                hideClickHologram_ = value;
                bitField0_ |= 0x00000080;
                onChanged();
                return this;
            }

            /**
             * <code>bool hide_click_hologram = 8;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearHideClickHologram() {
                bitField0_ = (bitField0_ & ~0x00000080);
                hideClickHologram_ = false;
                onChanged();
                return this;
            }

            private boolean tunnelVision_;

            /**
             * <code>bool tunnel_vision = 9;</code>
             *
             * @return The tunnelVision.
             */
            @java.lang.Override
            public boolean getTunnelVision() {
                return tunnelVision_;
            }

            /**
             * <code>bool tunnel_vision = 9;</code>
             *
             * @param value The tunnelVision to set.
             * @return This builder for chaining.
             */
            public Builder setTunnelVision(boolean value) {

                tunnelVision_ = value;
                bitField0_ |= 0x00000100;
                onChanged();
                return this;
            }

            /**
             * <code>bool tunnel_vision = 9;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTunnelVision() {
                bitField0_ = (bitField0_ & ~0x00000100);
                tunnelVision_ = false;
                onChanged();
                return this;
            }

            private boolean resilient_;

            /**
             * <code>bool resilient = 10;</code>
             *
             * @return The resilient.
             */
            @java.lang.Override
            public boolean getResilient() {
                return resilient_;
            }

            /**
             * <code>bool resilient = 10;</code>
             *
             * @param value The resilient to set.
             * @return This builder for chaining.
             */
            public Builder setResilient(boolean value) {

                resilient_ = value;
                bitField0_ |= 0x00000200;
                onChanged();
                return this;
            }

            /**
             * <code>bool resilient = 10;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearResilient() {
                bitField0_ = (bitField0_ & ~0x00000200);
                resilient_ = false;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:dev.foxikle.customnpcs.internal.proto.Settings)
        }

        // @@protoc_insertion_point(class_scope:dev.foxikle.customnpcs.internal.proto.Settings)
        private static final dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings();
        }

        public static dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Settings>
                PARSER = new com.google.protobuf.AbstractParser<Settings>() {
            @java.lang.Override
            public Settings parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Settings> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Settings> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public dev.foxikle.customnpcs.internal.proto.SettingsOuterClass.Settings getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_dev_foxikle_customnpcs_internal_proto_Settings_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_dev_foxikle_customnpcs_internal_proto_Settings_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016settings.proto\022%dev.foxikle.customnpcs" +
                        ".internal.proto\"\330\001\n\010Settings\022\026\n\016schema_v" +
                        "ersion\030\001 \001(\005\022\r\n\005value\030\002 \001(\t\022\021\n\tsignature" +
                        "\030\003 \001(\t\022\021\n\tskin_name\030\004 \001(\t\022\027\n\017custom_holo" +
                        "gram\030\005 \001(\t\022\014\n\004name\030\006 \001(\t\022\021\n\tclickable\030\007 " +
                        "\001(\010\022\033\n\023hide_click_hologram\030\010 \001(\010\022\025\n\rtunn" +
                        "el_vision\030\t \001(\010\022\021\n\tresilient\030\n \001(\010b\006prot" +
                        "o3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_dev_foxikle_customnpcs_internal_proto_Settings_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_dev_foxikle_customnpcs_internal_proto_Settings_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_dev_foxikle_customnpcs_internal_proto_Settings_descriptor,
                new java.lang.String[]{"SchemaVersion", "Value", "Signature", "SkinName", "CustomHologram", "Name", "Clickable", "HideClickHologram", "TunnelVision", "Resilient",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
