name: Gradle Compile Check

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - run: chmod +x gradlew

      - name: Assemble
        run: ./gradlew assemble
